### ISSUE TITLE
文字内容过多，超过1行的处理

### ISSUE THREAD

**Issue by zongyao2** [lygttpod/SuperTextView#1]
1、像 sample 中 layout3 这种情况，2边都是文字的情况时，是否考虑2段文字的左右间距 和 是否最多只能显示1行，否则会2边的文字会引起重叠；

2、其他布局也同样道理，希望提供一个是否允许文字最多显示 1 行的开关。

**Comment by lygttpod** [comment]
@zongyao2 描述的问题已修复，v1.0.2版本已提交审核，明天应该会审核通过，到时候你试试compile 'com.allen.supertextview:supertextview:1.0.2'  看看是否解决你的问题

**Comment by nyakokishi** [comment]
@lygttpod 试试这个https://jitpack.io/，不需要审核

**Comment by zongyao2** [comment]
@lygttpod 好的，赞
