### ISSUE TITLE
ImageView能否加个tint着色属性

### ISSUE THREAD

**Issue by AIlll** [lygttpod/SuperTextView#100]
左右的icon，我发现没有```android:tint="@color/white"```这个属性，有些地方同一个图标，需要显示不同颜色

**Comment by lygttpod** [comment]
@AIlll 可以获取对应的imageview对象例如stv.getLeftIconIV().setColorFilter();代码动态处理tint

**Comment by AIlll** [comment]
@lygttpod 这样也行，我是觉得xml里会好一些..  可以少写一些java代码。。

**Comment by lygttpod** [comment]
[看下这个](https://github.com/lygttpod/SuperTextView/issues/72)
属性过多导致无法预览的问题还没解决，所有目前有很多属性都是通过代码控制的，没有加到xml属性中
