### ISSUE TITLE
 stv:sLeftTextColor="@color/home_my_selector_text_blue" 没有效果

### ISSUE THREAD

**Issue by as11051105** [lygttpod/SuperTextView#103]
stv:sLeftTextColor="@color/home_my_selector_text_blue" 没有效果

**Comment by lygttpod** [comment]
有效果的哦，看下是不是哪里写错了
![image](https://user-images.githubusercontent.com/11826777/38283309-df7d34ec-37e7-11e8-908a-7f17c2934746.png)

**Comment by as11051105** [comment]
字体颜色设置selecter，常态和点击态，点击按下的颜色无效
