### ISSUE TITLE
SupterTextView设置背景问题

### ISSUE THREAD

**Issue by jingzhanwu** [lygttpod/SuperTextView#105]
SupterTextView 设置背景后，它的背景和整个根布局的背景反过来了

**Comment by lygttpod** [comment]
对STV设置背景怎么会影响跟布局纳  是不是哪里写错了，发下你的配置信息看看

**Comment by jingzhanwu** [comment]
根布局

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/page_bg"
    android:orientation="vertical">
  ........
  .........


 <com.allen.library.SuperTextView
                android:id="@+id/ll_my_performance"
                style="@style/super_text_left_center_right_arrow"
                android:layout_marginTop="10dp"
                app:sLeftIconRes="@drawable/user_iv_performance"
                app:sLeftTextString="@string/user_performance"
                app:sUseRipple="true" />

<style name="super_text_right_arrow" parent="match_width">
        <item name="android:layout_height">@dimen/size_48</item>
        <item name="sDividerLineType">none</item>
        <item name="sRightIconRes">@drawable/icon_right_arrow</item>
        <item name="sLeftTextSize">@dimen/font_size_15sp</item>
        <item name="sRightTextSize">@dimen/font_size_13sp</item>
        <item name="sCenterTextSize">@dimen/font_size_13sp</item>
        <item name="sRightTextGravity">right</item>
        <item name="sRightTextColor">@color/black_a</item>
        <item name="sCenterTextColor">@color/black</item>
        <item name="android:background">@color/pure_white</item>
    </style>


Gradle 配置
 /*SuperTextView*/
    compile "com.github.lygttpod:SuperTextView:$rootProject.ext.superTextView"
    /*腾讯ui框架*/
    api "com.qmuiteam:qmui:$rootProject.ext.qmui"
    .....
    .....

**Comment by lygttpod** [comment]
没看到设置背景的相关代码，麻烦贴清楚一下或者加QQ群688433795详细说明
