### ISSUE TITLE
如何设置显示省略号?

### ISSUE THREAD

**Issue by LauRocky** [lygttpod/SuperTextView#106]
用下面的这种方式,设置后,不能正确显示省略号,请求该如何设置
```
            stv:sLeftLines="1"
            stv:sLeftMaxEms="15"
```

**Comment by lygttpod** [comment]
请参考demo中在列表中显示的布局配置

**Comment by LauRocky** [comment]
感谢回复.
你说的demo,应该是指https://github.com/lygttpod/SuperTextView/tree/master/app这个路径下的代码吧.
我看了一下,并没有找到相关的配置.
是demo的路径不正确吗?如果是,麻烦给一个demo的路径,多谢.

**Comment by lygttpod** [comment]
简单样式支持省略号[demo](https://github.com/lygttpod/SuperTextView/blob/master/app/src/main/res/layout/item.xml)
左中右并存的结构暂不支持
