### ISSUE TITLE
使用useshpe后,底部分割线就不能用了吗

### ISSUE THREAD

**Issue by mengbixiusi** [lygttpod/SuperTextView#108]

**Comment by lygttpod** [comment]
是的，因为shape是对整个stv的背景设置的，按理说使用了shape就不应该出现分割线了
所以源码中做了判断

![image](https://user-images.githubusercontent.com/11826777/39686541-3ac8502e-51fc-11e8-8c22-d090149051e0.png)

**Comment by mengbixiusi** [comment]
谢谢解答,明白了.已给星

**Comment by 932707629** [comment]
> 谢谢解答,明白了.已给星

可是如果是我topLeft topRight设置圆角  bottom没有设置呢
