### ISSUE TITLE
设置字体颜色不支持selector

### ISSUE THREAD

**Issue by Zvirtuey** [lygttpod/SuperTextView#113]
XML配置属性无效：
stv:sCenterTextColor="@color/selector_tv_number"

代码配置也没用：
holder.stvNum.setCenterTextColor(mContext.getResources().getColor(R.color.selector_tv_number));

是不是不支持呢？

**Comment by lygttpod** [comment]
问题已修复，请使用最新版2.1.8，使用说明请看 [更新日志](https://github.com/lygttpod/SuperTextView/releases)
