### ISSUE TITLE
recycleview 中加载大量图片的时候数据错乱

### ISSUE THREAD

**Issue by longzekai** [lygttpod/SuperTextView#114]
不知道为啥在recycleview 中加载大量图片的时候会数据错乱，有人碰到么？

**Comment by longzekai** [comment]
具体我还没去研究，赶项目，我自己重写了，但是我Glide 一样的代码，用其他的控件，没有出现图片数据错乱的问题哦。

**Comment by lygttpod** [comment]
自定义view你要做复用处理

**Comment by longzekai** [comment]
Glide 不是已经帮你处理了资源复用的问题了么？我在其他的recycleview 中，使用Glide 正常加载图片，有没有碰到数据错乱的问题啊。

**Comment by lygttpod** [comment]
adapter中自定义view你要做复用处理，搞个list缓存自定义view就好了，如有疑问可入群讨论

**Comment by lygttpod** [comment]
@longzekai 问题解决了吗
