### ISSUE TITLE
请问以下效果怎么实现？

### ISSUE THREAD

**Issue by MinchinWang** [lygttpod/SuperTextView#116]
![1538204905210](https://user-images.githubusercontent.com/3407244/46242287-8b87b580-c3f9-11e8-9811-61eec4ef89d0.jpg)
请问这种效果怎么x实现？

**Comment by lygttpod** [comment]
如果是图片就不用说了，是文字的话使用一个textview配合SpannableString就行，具体用法搜索《SpannableString 设置文字圆角背景》既有相关介绍
