### ISSUE TITLE
嵌套SuperTextView使用，父类不能获得点击事件

### ISSUE THREAD

**Issue by liyanmei** [lygttpod/SuperTextView#120]
`<com.allen.library.SuperTextView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/layoutParent"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:sShapeSelectorNormalColor="@color/colorPrimary"
    app:sShapeSelectorPressedColor="@color/colorPrimary"
    app:sUseShape="true">

    <com.allen.library.SuperTextView
        android:id="@+id/layoutChild"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_100"
        app:sShapeSelectorNormalColor="@color/color_font_wihte"
        app:sShapeSelectorPressedColor="@color/color_font_wihte"
        app:sUseShape="true" />

    <com.allen.library.SuperTextView
        android:id="@+id/layoutChild2"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_100"
        android:layout_centerVertical="true"
        app:sShapeSelectorNormalColor="@color/color_5A97FB"
        app:sShapeSelectorPressedColor="@color/color_5A97FB"
        app:sUseShape="true" />

</com.allen.library.SuperTextView>`

`
public class TestActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.aa_test);

        findViewById(R.id.layoutChild).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.e("kkkk ", "onClick: 点击 layoutChild");
            }
        });

        findViewById(R.id.layoutParent).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.e("kkkk ", "onClick: 点击 layoutParent=================");
            }
        });

        findViewById(R.id.layoutChild2).clearFocus();

    }
}`

当点击layoutChild2区域的时候，layoutParent这个的点击事件不能执行。
有没有办法屏蔽到子类中所有的点击事件，只执行父类中的事件

**Comment by lygttpod** [comment]
子view设置sUseRipple属性为false即可
