### ISSUE TITLE
莫名多了一条分割线!!!

### ISSUE THREAD

**Issue by lydlovezjr** [lygttpod/SuperTextView#122]
![_20181026175455](https://user-images.githubusercontent.com/19246347/47559594-7e061280-d948-11e8-81e3-b00a5ebb7326.png)
   <LinearLayout
        style="@style/hh_fi_wr"
        android:background="@color/white"
        android:orientation="vertical">

        <com.allen.library.SuperTextView
            android:id="@+id/tv_change_phone"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:sLeftTextColor="@color/black_text"
            stv:sLeftTextSize="@dimen/sp_16"
            stv:sLeftTextString="手机号:13213071373"
            stv:sRightIconRes="@drawable/right_arrow"/>

        <com.allen.library.SuperTextView
            android:id="@+id/tv_change_address"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:sLeftTextColor="@color/black_text"
            stv:sLeftTextSize="@dimen/sp_16"
            stv:sLeftTextString="我的地址:河南省郑州市金林公馆"
            stv:sRightIconRes="@drawable/right_arrow"/>

    </LinearLayout>

**Comment by lygttpod** [comment]
默认是显示下分割线的

**Comment by lydlovezjr** [comment]
谢了
