### ISSUE TITLE
集成运行报错

### ISSUE THREAD

**Issue by jackandroid2016** [lygttpod/SuperTextView#123]
![image](https://user-images.githubusercontent.com/19246186/47829252-5d631000-ddc1-11e8-85a2-7d3049b1de42.png)
环境：Android studio 3.2
compileSdkVersion 28
系统资源冲突

**Comment by ousq** [comment]
也是是的

**Comment by lygttpod** [comment]
这位小伙伴的运行报错问题解决了吗
