### ISSUE TITLE
stv:sLeftTextString= 一行长文字 显示不下

### ISSUE THREAD

**Issue by SomnusWu** [lygttpod/SuperTextView#124]
stv:sLeftTextString=“长文字~~~~”
类似这个布局 ，文字很长的时候

 
![](https://user-images.githubusercontent.com/7221064/47059174-b431ec80-d1fa-11e8-913e-1fbc5723dbf3.png)

**Comment by lygttpod** [comment]
字符很长的时候会自动换行，如果是说是文字覆盖到右侧图片的话，设置sLeftViewMarginRight属性即可解决
