### ISSUE TITLE
字体样式不能动态设置

### ISSUE THREAD

**Issue by zyw745293** [lygttpod/SuperTextView#128]
没有找到像SpannableString.setSpan(Object what, int start, int end, int flags)这种方法。     我项目中有些内容是动态从数据库中读取后展示在TextView上的，且内容文本量比较大。
       比如类似如下内容，需要将均价、位置、电话以不同颜色样式进行匹配后区别显示。用SpannableString的这个方法可以实现，但是比较麻烦。

北大资源海樾府
均价： 12600元/平米
位置： 重庆市江北区海尔路599号
电话： 4000352327转4036

中交中央公园
均价： 14400元/平米
位置： 重庆市渝北区中央公园东路西南侧 
电话： 4000352327转8395

碧桂园中俊天玺
均价： 17000元/平米
位置： 重庆市两江新区照母山金渝大道中段天来酒店 
电话： 4000352360转9621

**Comment by lygttpod** [comment]
样式的话就直接使用SpannableString自己对字符串做样式的定制然后传入stv即可，就是原生的TextView也要通过SpannableString去定制样式的，所以要自己去处理喽
