### ISSUE TITLE
怎么在右边添加头像图片+箭头

### ISSUE THREAD

**Issue by rmtic** [lygttpod/SuperTextView#13]
例如（模板样子）：
---------------------------------------------
帐号                                         用户头像 >
---------------------------------------------
开发的工程中，需要 【用户头像+箭头】的组合
我发现 在xml中 可以通过sRightTextStringRightIconRes，修改用户头像的图片；
但是在代码中确无法修改用户头像，请问在代码中我该怎么修改。

我用的是Picasso加载图片，我发现SuperTextView，只有rightImageViewId
Picasso.with(this)
                .load("http://i.imgur.com/DvpvklR.png")
                .placeholder(R.drawable.ease_default_image)
                .into((ImageView) stvGroupChatAvatar.getView(SuperTextView.rightImageViewId));

**Comment by lygttpod** [comment]
@rmtic 
6.使用第三方库(Picasso或者Glide)加载网络图片

     Picasso.with(this)
     .load(url)
     .placeholder(R.drawable.head_default)
     .into((ImageView) superTextView.getView(SuperTextView.leftImageViewId));

**Comment by rmtic** [comment]
不是在最左边加图片，我的意思是在最右边，添加    格式如下 :   帐号文本-----------------   头像图片 >

**Comment by lygttpod** [comment]
@rmtic 右边目前只支持设置一张照片，要么显示头像，要么显示箭头，暂时还不支持显示两张图

**Comment by rmtic** [comment]
好的，非常感谢，你写的库真的很好用！

**Comment by ljf1172361058** [comment]
我也是觉得有右边有 xxx>这样的形式比较好
另外 作者你可以完善这个库的的效果么,感觉它的库也有可以值得借鉴的地方,链式调用,一行代码搞定list
这个调用起来比较方便的
http://www.xiufm.com/thread-14616-1-1.html

**Comment by lygttpod** [comment]
@ljf1172361058 @rmtic 
SuperTextView2.0.0已上线，可以满足你的要求，欢迎使用并提供意见

**Comment by rmtic** [comment]
谢谢你🙏
