### ISSUE TITLE
superTextView 不支持渐变色吗？

### ISSUE THREAD

**Issue by LeslieKoma** [lygttpod/SuperTextView#130]
老哥：我现在的需求如下
1. 一个圆角的左右渐变的中间设置图片的按钮
2.superTextView不支持渐变色
3.superButton不支持中间插入图片
4.[效果图在这里](https://i.loli.net/2018/12/07/5c09e4a781ebb.png)
 现在考虑的是直接用线形布局，或者UI中间的微信登录改为文字

**Comment by lygttpod** [comment]
stv目前不支持渐变效果，可以对stvsBackgroundDrawableRes属性设置一个渐变的shape文件即可
