### ISSUE TITLE
渲染程度你考虑了吗？

### ISSUE THREAD

**Issue by KevinLiu9527** [lygttpod/SuperTextView#131]
我使用这个控件，但是使用开发者打开渲染程度，发现渲染程度非常严重，这会导致app运行的性能问题，这个你有没有想过解决一下

**Comment by lygttpod** [comment]
## 开发者模式打开过渡绘制模式显示如下，并没有过渡绘制


![image](https://user-images.githubusercontent.com/11826777/54609748-85ac8c00-4a8e-11e9-8d96-2ac5820528fb.png)
