### ISSUE TITLE
左右文字重叠，如何让右边文字在左侧的右边

### ISSUE THREAD

**Issue by softsnow** [lygttpod/SuperTextView#133]
![image](https://user-images.githubusercontent.com/20201897/50581718-1cf24200-0e97-11e9-8ece-4750a668250c.png)

**Comment by softsnow** [comment]
左边和z中间的文字可以实现这种效果，左边和右边文字如何实现这种效果![image](https://user-images.githubusercontent.com/20201897/50581731-3b583d80-0e97-11e9-8a97-183830043f10.png)

**Comment by lygttpod** [comment]
修改这个属性值 sCenterViewGravity

**Comment by softsnow** [comment]
用这个属性sCenterViewGravity不是得用sCenterTextString？我如果想要sLeftTextString和sRightTextString实现右边文字自动换行，设置sCenterViewGravity管用吗？这个只是中间BaseTextView的位置啊

**Comment by singlenoah** [comment]
> 
> 
> 用这个属性sCenterViewGravity不是得用sCenterTextString？我如果想要sLeftTextString和sRightTextString实现右边文字自动换行，设置sCenterViewGravity管用吗？这个只是中间BaseTextView的位置啊

我也发现了这个问题.相同的疑问.
同时用sLeftTextString和sRightTextString实现右边文字自动换行无法实现,

**Comment by lygttpod** [comment]
同时用sLeftTextString和sRightTextString无法实现的效果，同时使用sLeftTextString和sCenterTextString就可以实现啊，为何要纠结是right还是center呐，在没有sRightTextString的情况下可以把sCenterTextString当right使用
