### ISSUE TITLE
TextView改用AppCompatTextView  并支持androidx

### ISSUE THREAD

**Issue by nameyuan** [lygttpod/SuperTextView#134]
android api19不能用矢量图，可以考虑改一下，用AppCompatTextView代替TextView，AppCompatTextView Google已经做了矢量图Vector支持，我复制了你的代码改了下用了

**Comment by lygttpod** [comment]
[V2.2.0](https://github.com/lygttpod/SuperTextView/releases/tag/2.2.0)中TextView已改用AppCompatTextView
