### ISSUE TITLE
默认的ripple效果导致圆角失效

### ISSUE THREAD

**Issue by Huazhiling** [lygttpod/SuperTextView#135]
在LinearLayout或者任意的Layout内嵌套SuperTextView，并且给外层layout设置圆角的background, 会导致外层layout的圆角不显示，原因是因为被SuperTextView的background覆盖了，但是我使用sUseRipple参数禁用之后，并且手动给SuperTextView设置了一个ripple，这时候外层圆角就有效果了

**Comment by lygttpod** [comment]
[V2.2.0](https://github.com/lygttpod/SuperTextView/releases/tag/2.2.0) 问题已修复  是应为库中ripple没设置id的问题  android:id="@android:id/mask"
