### ISSUE TITLE
如何设置view不可点击

### ISSUE THREAD

**Issue by mingmingacc** [lygttpod/SuperTextView#136]
发现work_sv.setEnabled(false);或是work_sv.setClickable(false);不起作用啊

**Comment by cdcdec** [comment]
如何设置view不可点击？？

**Comment by cdcdec** [comment]
默认点击后会出现一个颜色变化   使用app:sUseRipple="false"  点击后不再有颜色变化了。

**Comment by lygttpod** [comment]
@cdcdec stv.setClickable(false) 就是不可点击，不可点击状态就不会出现点击颜色变化效果
