### ISSUE TITLE
isShowBottomDivider 这个方法不管用

### ISSUE THREAD

**Issue by guoleifei** [lygttpod/SuperTextView#139]
![image](https://user-images.githubusercontent.com/16201257/56034767-e318bd80-5d5a-11e9-9d84-2516eb789613.png)
设置完成以后重绘，但是判断的还是
  mIsShowBottomDivider = (BOTTOM == mDividerLineType || BOTH == mDividerLineType); 所以无效

**Comment by lygttpod** [comment]
### 问题已修复[V2.2.1](https://github.com/lygttpod/SuperTextView/releases/tag/2.2.1)
### 新增setDividerLineType()方法动态设置分割线
