### ISSUE TITLE
进程杀死，状态和内容会保存吗

### ISSUE THREAD

**Issue by dyfan** [lygttpod/SuperTextView#143]
hello，我自己自定义了一个类似的组合控件，暂且叫他ItemGroup。用在一个页面，这个页面有多个ItemGroup，在进程在后台被杀死，用户切换回来的时候，显示内容就会混乱，我google一下和view的onSaveInstanceState和onRestoreInstanceState方法有关，不知道您这个是否考虑这个问题。

**Comment by lygttpod** [comment]
目前没有特殊处理过异常情况保存状态的逻辑

**Comment by dyfan** [comment]
好的，不过我看您这个没有使用layout布局文件，应该不会存在混乱的这个情况。感谢开源。
