### ISSUE TITLE
关于点击事件

### ISSUE THREAD

**Issue by yaojunqi** [lygttpod/SuperTextView#144]
目前的点击事件是针对每个字的监听，可否添加一种监听是：对左边的全部设为一个整体的监听
 
如：左边有上下中 三个tvString，我点击左边任意一块位置都触发，甚至是空白处
空白的范围和权重一样，平分大小

**Comment by lygttpod** [comment]
已修复 [v2.2.4更新说明](https://github.com/lygttpod/SuperTextView/releases/tag/2.2.4)
