### ISSUE TITLE
宽度是填充父布局的，只能把宽度写成固定的吗， 宽度能不能根据自身内容来自适应

### ISSUE THREAD

**Issue by zhaoxiuyu** [lygttpod/SuperTextView#145]
宽度是填充父布局的，只能把宽度写成固定的吗， 宽度能不能根据自身内容来自适应

**Comment by DaveBoy** [comment]
确实有这个问题  本来都集成好了  因为这个问题又得撤回来，我看issues说2.2就支持wrap了 但是实际上高度可以，宽度并不可以
环境：AndroidX中的ConstraintLayout布局之中

**Comment by lygttpod** [comment]
因为STV继承RelativeLayout，内部右边有占位view使用的是ALIGN_PARENT_RIGHT属性，就会撑满RelativeLayout，所以设置wrap_content无效

@DaveBoy 正常使用RelativeLayout,内部右边子view使用layout_alignParentRight属性的话也是无法在ConstraintLayout中使用的
