### ISSUE TITLE
superButton的宽度自适应

### ISSUE THREAD

**Issue by HaleyHong** [lygttpod/SuperTextView#147]
自适应padding太大，不能自己设置；不能像Button通过 android:minHeight="0dp"，android:minWidth="0dp"来自适应

**Comment by lygttpod** [comment]
1、SuperButton继承自AppCompatButton，理论上正常button怎么使用他也一样；
2、SuperButton内部实现已经抽离出ShapeBuilder类处理，可以对任意view设置ShapeBuilder即可实现圆角等操作，不局限于使用button
