### ISSUE TITLE
RecyclerView  item 点击事件

### ISSUE THREAD

**Issue by gdmec07140644** [lygttpod/SuperTextView#149]
item 布局里面有用SupertextView 作为子view ，然后里面又嵌套了几个SuperTextView作为按钮，按钮的useRiple 为true，父SuperTextView useRiple为false，但是item点击事件没用，请问为什么啊
![image](https://user-images.githubusercontent.com/14285067/64266630-7ac7b400-cf67-11e9-837a-2dfc77bcdb5a.png)

**Comment by lygttpod** [comment]
想要使用item点击事件就要设置SupertextView的useRiple为false，使用useRiple的话就会默认处理点击事件
