### ISSUE TITLE
楼主我升级到从1.0.4升级1.0.8,发现文本中的字都不见了,向下兼容得提高一下下？还有一个问题,为何觉得精简版的比主要版的功能更多,文档更详细,两者是否兼容？

### ISSUE THREAD

**Issue by ljf1172361058** [lygttpod/SuperTextView#15]

**Comment by lygttpod** [comment]
@ljf1172361058 
1.0.4到1.0.8中间跨越了几个版本  架构有些变化  可能会导致部分属性无效（这种情况应该不多），建议根据新的文档或者demo编写，精简版是实现方式精简了 功能点少了几个，比如checkbox去掉了，里边所有实现方式最多只有三个textView去实现，相比之前用textview，imageview，checkbox等精简了，但功能点不相上下，毕竟我们这个框架只是SuperTextView，另外SuperTextView和CommonTextView是两个不同的类  方法属性都不同，建议使用时候参考文档及demo去实现。

**Comment by ljf1172361058** [comment]
@lygttpod 
多谢。
我感觉我还是用CommonTextView吧,毕竟是在有经验的情况下重新编写的.可靠,哈哈
