### ISSUE TITLE
使用Glide 4.9.0设置左边图片时候会出现BUG

### ISSUE THREAD

**Issue by Iverlei** [lygttpod/SuperTextView#150]
在经过您的Demo上测试过，在你的带图片类中，我用Glide 4.9.0 写下
`Glide.with(this)
                .load(url1)
                .into(superTextView.getLeftIconIV());`
会出现本来应该是出现在左边的icon显示到了中间，现在还没看出来为什么，但是加上占位图片就又回显示正确，使用target重新设置也是会正确。

**Comment by lygttpod** [comment]
解决办法：设置IV的宽高即可
```
            stv:sLeftIconHeight="60dp"
            stv:sLeftIconWidth="60dp"
```
原因：因为STV中IV默认没有宽高都是wrap_content，不设置宽高Glide就会把IV设为match_parent铺满，就会出现你描述的问题，添加placeholder的话他会按照placeholder的图片大小去设置，如果placeholder的图片很大一样会出现问题，所以最好的解决方法就是设置图片宽高
