### ISSUE TITLE
databinding下不显示

### ISSUE THREAD

**Issue by chenwuwen** [lygttpod/SuperTextView#151]
SuperTextView:2.2.4
AndroidStudio 3.5
在AS下，使用STV，可以预览，但是安装到手机上后不显示文字和图片，但是可以点击，有水波纹效果，是不支持吗？还是我哪里设置出错了？（当我去掉Databinding标签时就显示了）

**Comment by lygttpod** [comment]
[查看issues91](https://github.com/lygttpod/SuperTextView/issues/91)
