### ISSUE TITLE
sSelectorPressedColor 能不能只对边框起效？

### ISSUE THREAD

**Issue by cdcdec** [lygttpod/SuperTextView#154]
sSelectorPressedColor 能不能只对边框起效，现在的是对整个背景起效。
另外：SuperButton 的Selector如果能支持图片就好了，就是不同的状态显示不同的图片，现在的只支持颜色

**Comment by lygttpod** [comment]
1、sSelectorPressedColor要相对只对边框起作用  就需要为每一种selector设置一套shape相关的属性，这就意味着至少需要三套重复的shape相关的属性，性价比不高，估暂时不考虑这种情况。
2、想要Selector支持图片就无法使用shape相关的属性了，因为当前的Selector是在设置shape的GradientDrawable中配置的，为了使用shape属性只能设置颜色不能设置图片

* 温馨提示：针对个别特殊需求，可以直接原始shape.xml  或者selector.xml 的方式实现

最后感谢对本库提的意见及对本库的支持，我们会不断完善尽量满足大部分需求（个别特殊需求，会根据性价比选择性的开发哦）
