### ISSUE TITLE
CommonTextView 监听问题

### ISSUE THREAD

**Issue by ljf1172361058** [lygttpod/SuperTextView#16]
使用过程中,发现默认整个CommonTextView的监听被子View给消费掉了,有时候需求就是只有整个CommonTextView可点击触发监听,而不需要为其子View设置监听,觉得默认只为CommonTextView设置监听就行,至于其子View的监听,只有用户为其设置了监听才可响应比较好

**Comment by lygttpod** [comment]
@ljf1172361058 这个问题已经修复

V1.1
修复SuperTextView和CommonTextView点击事件被子View消耗掉的bug（具体使用请参考文档）

**Comment by ljf1172361058** [comment]
@lygttpod 多谢修复,我现在更新最新版本
