### ISSUE TITLE
布局预览正常 模拟器和手机不显示的问题

### ISSUE THREAD

**Issue by MyAcooL** [lygttpod/SuperTextView#162]
![image](https://user-images.githubusercontent.com/21095161/69536474-fb231180-0fb8-11ea-8f31-46dea3fae9b2.png)
![image](https://user-images.githubusercontent.com/21095161/69536485-024a1f80-0fb9-11ea-8bdd-e4617d161674.png)

手机和模拟器显示是一样的 显示不出来

**Comment by lygttpod** [comment]
看你布局文件中命名空间定义了多个，app和stv混用了，统一处理 都修改为app或者都修改stv即可
