### ISSUE TITLE
gradientCenterX，gradientCenterY不是dimension，应该是float

### ISSUE THREAD

**Issue by Sigasiiiiii** [lygttpod/SuperTextView#164]
/**
     * Sets the position of the center of the gradient as a fraction of the
     * width and height.
     * <p>
     * The default value is (0.5, 0.5).
     * <p>
     * <strong>Note</strong>: changing this property will affect all instances
     * of a drawable loaded from a resource. It is recommended to invoke
     * {@link #mutate()} before changing this property.
     *
     * @param x the X-position of the center of the gradient
     * @param y the Y-position of the center of the gradient
     *
     * @see #mutate()
     * @see #setGradientType(int)
     * @see #getGradientCenterX()
     * @see #getGradientCenterY()
     */
    public void setGradientCenter(float x, float y) {
        mGradientState.setGradientCenter(x, y);
        mGradientIsDirty = true;
        invalidateSelf();
    }

**Comment by lygttpod** [comment]
Thank you for your question，i will fix it on the next version

**Comment by lygttpod** [comment]
已修复
