### ISSUE TITLE
图片预览问题

### ISSUE THREAD

**Issue by ShirleyLuoppx** [lygttpod/SuperTextView#167]
建议作者可以给项目描述的时候加上一些效果图方便第一次看该项目的伙伴大概知道有哪些效果哈

**Comment by lygttpod** [comment]
## 文档里边有效果图片
![image](https://user-images.githubusercontent.com/11826777/71442060-3abb5580-273f-11ea-958d-cec5155173d2.png)

**Comment by ShirleyLuoppx** [comment]
fine   当时图片没有加载出来吧   就像现在一样  sorry

**Comment by ShirleyLuoppx** [comment]
> ## 文档里边有效果图片
> ![image](https://user-images.githubusercontent.com/11826777/71442060-3abb5580-273f-11ea-958d-cec5155173d2.png)

fine 当时图片没有加载出来吧 就像现在一样 sorry
