### ISSUE TITLE
关于ShapeBuilder类配置常量优化的建议

### ISSUE THREAD

**Issue by magic0908** [lygttpod/SuperTextView#174]
感谢作者的开源库，不过我觉得有些地方的代码可以优化下。
ShapeBuilder里面的常量都是普通Int类型，比如定义android:shape，
代码setShapeType(shapeType: Int)，因为参数是Int类型，有可能添加参数的时候会写成其他常量。就会引发问题。我觉得可以参考ViewCompat类，使用注解定义这些常量，将其分组，这样在使用的时候更加直观。

**Comment by lygttpod** [comment]
非常感谢提的优化意见，为了不引入注解代码就把ShapeBuilder常量中使用枚举处理了，可以拉最新代码看下
