### ISSUE TITLE
分割线不显示

### ISSUE THREAD

**Issue by iSally** [lygttpod/SuperTextView#177]
sUseShape 为true也不显示 不知道为啥

**Comment by singlenoah** [comment]
设置分割线相关属性为  `sDividerLine`

**Comment by lygttpod** [comment]
<com.allen.library.SuperTextView
                android:layout_width="match_parent"
                android:layout_height="50dp"
                android:layout_marginTop="50dp"
                stv:sDividerLineType="both"
                stv:sDividerLineColor="@color/red_btn"
                stv:sDividerLineHeight="5dp"
                stv:sLeftTextString="分割线用法"
                stv:sRightIconRes="@drawable/arrow_right_red" />
