### ISSUE TITLE
子SuperTextView 自动拦截了父控件的点击事件么？请修改？

### ISSUE THREAD

**Issue by itcheng** [lygttpod/SuperTextView#178]
<LinearLayout
    android:id="@+id/proom_setting_psw_ll"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="2dp"
    android:orientation="horizontal"
    android:paddingBottom="36dp"
    app:layout_constraintTop_toBottomOf="@+id/proom_setting_encryption">

    <com.allen.library.SuperTextView
        android:id="@+id/proom_setting_psw_0"
        android:layout_width="36dp"
        android:layout_height="36dp"
        android:layout_marginRight="10dp"
        android:clickable="false"
        app:sCenterTextColor="@color/c_333333"
        app:sCenterTextSize="15sp"
        app:sCenterTextString=""
        app:sShapeCornersRadius="6dp"
        app:sShapeSelectorNormalColor="#fff7f6f9"
        app:sShapeSelectorPressedColor="#fff7f6f9"
        app:sUseShape="true" />

    <com.allen.library.SuperTextView
        android:id="@+id/proom_setting_psw_1"
        android:layout_width="36dp"
        android:layout_height="36dp"
        android:layout_marginRight="10dp"
        android:clickable="false"
        app:sCenterTextColor="@color/c_333333"
        app:sCenterTextSize="15sp"
        app:sCenterTextString=""
        app:sShapeCornersRadius="6dp"
        app:sShapeSelectorNormalColor="#fff7f6f9"
        app:sShapeSelectorPressedColor="#fff7f6f9"
        app:sUseShape="true" />

    <com.allen.library.SuperTextView
        android:id="@+id/proom_setting_psw_2"
        android:layout_width="36dp"
        android:layout_height="36dp"
        android:layout_marginRight="10dp"
        android:clickable="false"
        app:sCenterTextColor="@color/c_333333"
        app:sCenterTextSize="15sp"
        app:sCenterTextString=""
        app:sShapeCornersRadius="6dp"
        app:sShapeSelectorNormalColor="#fff7f6f9"
        app:sShapeSelectorPressedColor="#fff7f6f9"
        app:sUseShape="true" />

    <com.allen.library.SuperTextView
        android:id="@+id/proom_setting_psw_3"
        android:layout_width="36dp"
        android:layout_height="36dp"
        android:layout_marginRight="10dp"
        android:clickable="false"
        app:sCenterTextColor="@color/c_333333"
        app:sCenterTextSize="15sp"
        app:sCenterTextString=""
        app:sShapeCornersRadius="6dp"
        app:sShapeSelectorNormalColor="#fff7f6f9"
        app:sShapeSelectorPressedColor="#fff7f6f9"
        app:sUseShape="true" />

</LinearLayout>

这种情况下设置

proom_setting_psw_ll 父控件的点击事件，如果点击在子的SuperTextView控件上，父控件会没有点击事件。是被SuperTextView给自动拦截了么？我没设置SuperTextView的点击事件 啊

​

**Comment by lygttpod** [comment]
[请参考issues112](https://github.com/lygttpod/SuperTextView/issues/112)
