### ISSUE TITLE
文字大小的单位看文档中用的是dp,不用sp的么?

### ISSUE THREAD

**Issue by ljf1172361058** [lygttpod/SuperTextView#18]
还是说SuperTextView中的文字大小单位用dp比较好

**Comment by lygttpod** [comment]
@ljf1172361058  字体设置的时候是用sp的  在内部会转换成px处理  我怎么没看到文档中用dp设置字体的地方。。。

**Comment by ljf1172361058** [comment]
2.布局中如何使用（列出所有属性使用方法）

    <com.allen.library.CommonTextView
            android:layout_width="match_parent"
            android:layout_height="50dp"

            //左边view的属性
            ctv:cLeftIconDrawablePadding="10dp"
            ctv:cLeftIconResForDrawableLeft="@drawable/uu"
            ctv:cLeftTextColor="@color/colorAccent"
            ctv:cLeftTextSize="15dp"
            ctv:cLeftTextString="左边文字"
            ctv:cLeftViewPaddingLeft="10dp"
            ctv:cLeftViewPaddingRight="10dp"

            //中间view的属性
            ctv:cCenterIconDrawablePadding="10dp"
            ctv:cCenterIconResForDrawableLeft="@drawable/uu"
            ctv:cCenterTextColor="@color/colorAccent"
            ctv:cCenterTextSize="15dp"
            ctv:cCenterTextString="中间文字"
            ctv:cCenterViewPaddingLeft="10dp"
            ctv:cCenterViewPaddingRight="10dp"

**Comment by ljf1172361058** [comment]
在 CommonTextView 的介绍中出现的

**Comment by lygttpod** [comment]
文档写错了。。。谢谢指出

**Comment by ljf1172361058** [comment]
不谢,应该是我谢谢你提供的开源库 @lygttpod
