### ISSUE TITLE
setShapeGradientStartColor,setShapeGradientEndColor android7.x系列闪退

### ISSUE THREAD

**Issue by pingxu** [lygttpod/SuperTextView#181]
setShapeGradientEndColor,setShapeGradientEndColor在android7.x系统会闪退
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.GradientDrawable$Orientation.ordinal()' on a null object reference

**Comment by lygttpod** [comment]
把xml及相关代码发下

**Comment by lygttpod** [comment]
已修复  请使用新版V2.4.6

[V2.4.6升级日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.4.6)

**Comment by pingxu** [comment]
多谢，辛苦
