### ISSUE TITLE
设置了sUseShape=true后填充色属（sShapeSolidColor）性仍然无效

### ISSUE THREAD

**Issue by JiangShuLiang** [lygttpod/SuperTextView#187]
如题，代码如下：
 <com.allen.library.SuperTextView
            android:layout_width="match_parent"
            android:layout_height="80dp"
            android:layout_marginTop="5dp"
            stv:sCenterBottomTextColor="@color/red"
            stv:sCenterBottomTextString="中下文字"
            stv:sCenterTopTextString=" "
            stv:sCenterViewGravity="left_center"
            stv:sLeftBottomTextColor="@color/yellow"
            stv:sLeftBottomTextString="左上文字"
            stv:sLeftIconHeight="30dp"
            stv:sLeftIconRes="@mipmap/ic_app_icon"
            stv:sLeftIconWidth="30dp"
            stv:sLeftTopTextColor="@color/blue"
            stv:sLeftTopTextString="左上文字"
            stv:sLeftViewGravity="left_center"
            stv:sRightViewType="switchBtn"
            stv:sShapeCornersRadius="10dp"
            stv:sShapeSolidColor="@color/green_light"
            stv:sShapeStrokeColor="@color/green"
            stv:sShapeStrokeWidth="1dp"
            stv:sThumbResource="@drawable/thumb"
            stv:sTrackResource="@drawable/track"
            stv:sUseRipple="true"
            stv:sUseShape="true" />

**Comment by lygttpod** [comment]
已修复  请使用新版V2.4.6

[V2.4.6升级日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.4.6)
