### ISSUE TITLE
可以设置分割线只marginLeft或只marginRight吗

### ISSUE THREAD

**Issue by AriesHoo** [lygttpod/SuperTextView#19]
可以设置分割线只marginLeft或只marginRight吗

**Comment by lygttpod** [comment]
暂不支持，目前好像还没遇到这个需求

supertextview的方法如下：
<attr name="sTopLineMargin" format="dimension" />
<attr name="sBottomLineMargin" format="dimension" />
<attr name="sBothLineMargin" format="dimension" />
commontextview的方法如下：
<attr name="cTopDividerLineMarginLR" format="dimension" />
<attr name="cBottomDividerLineMarginLR" format="dimension" />
<attr name="cBothDividerLineMarginLR" format="dimension" />


lygttpod@163.com
 
发件人： Aries
发送时间： 2017-02-14 10:57
收件人： lygttpod/SuperTextView
抄送： Subscribed
主题： [lygttpod/SuperTextView] 可以设置分割线只marginLeft或只marginRight吗 (#19)
可以设置分割线只marginLeft或只marginRight吗

**Comment by AriesHoo** [comment]
像支付宝 我的 及 设置 界面的中间的item就是只设置了marginLeft的

**Comment by lygttpod** [comment]
@AriesHoo 好像真是呦，忙完这段时间会考虑加上这个功能

**Comment by lygttpod** [comment]
@AriesHoo 
#更新日志

V1.1.2

上下分割线添加单独设置左右边距的参数

        1、SuperTextVIew配置方法如下:下列两种方式都是单独使用
        
        //方法一
        stv:sTopLineMarginLeft="10dp"
        stv:sTopLineMarginRight="0dp"
         
        stv:sBottomLineMarginLeft="10dp"
        stv:sBottomLineMarginRight="0dp"
        
        //方法二
        stv:sBothLineMarginLeft="10dp"
        stv:sBothLineMarginRight="0dp"
                        
        2、CommonTextView配置方法如下：下列两种方式都是单独使用
        
        //方法一
        ctv:cTopDividerLineMarginLeft="10dp"
        ctv:cTopDividerLineMarginRight="0dp"

        ctv:cBottomDividerLineMarginLeft="10dp"
        ctv:cBottomDividerLineMarginRight="0dp"
        
        //方法二
        ctv:cBothDividerLineMarginLeft="10dp"
        ctv:cBothDividerLineMarginRight="0dp"
