### ISSUE TITLE
做得很好~不过要少用private，不然很难继承定制

### ISSUE THREAD

**Issue by TangentLu666** [lygttpod/SuperTextView#2]
每个人都有定制的需求，希望SuperTextView内的方法和变量不要用private，而是用protect，这样我就能复写你的方法然后和方便地做出自己想要的空间了，望采纳，谢谢！

**Comment by lygttpod** [comment]
@TangentLu666 谢谢您的反馈，下个版本会采取您的建议！会不断完善这个库！
