### ISSUE TITLE
代码设置shapeCornersRadius

### ISSUE THREAD

**Issue by zhuaishinanrendebenxing** [lygttpod/SuperTextView#200]
版本号：2.4.2
在代码中使用shapebuilder的shapeCornersRadius属性不起作用

`ShapeBuilder shapeBuilder1 = new ShapeBuilder();
shapeBuilder1.setShapeCornersRadius(50.0f);
shapeBuilder1.into(textview)`

**Comment by lygttpod** [comment]
请使用最新版本
