### ISSUE TITLE
这样排版，可以支持一下？

### ISSUE THREAD

**Issue by jeffreyxuworld** [lygttpod/SuperTextView#201]
这样排版，可以支持一下？
例如：第一行中有小标签图片或者带背景的TextView+文字，但是有很多行，第一行文字在小标签图片的右边，第二行文字和图片居左对齐。

（小标签）+ 文字文字文字文字文字文字文字文字文字   -> 第一行
文字文字文字文字文字文字文字文字文字文字文字文      -> 第二行

**Comment by lygttpod** [comment]
《小标签图片或者带背景的TextView+文字》这种特殊需求的话直接使用Span去实现就好了，SuperTextView不可能满足所以的布局哦
