### ISSUE TITLE
建议添加圆角

### ISSUE THREAD

**Issue by gmlymayday** [lygttpod/SuperTextView#25]

**Comment by lygttpod** [comment]
圆角可以通过shape编写，设为背景就可以了

**Comment by Hn1993** [comment]
直接用第三方库加载圆角图片就行了吧

**Comment by cwyrzz** [comment]
赞成，更多时候是希望填充背景颜色，直接设置圆角，不想一个颜色去写一个shape

**Comment by lygttpod** [comment]
有的说是吧图片设置圆角有的是设置整个布局圆角，需求描述详细一点，可以的话配上效果图，哈哈，我看看会在后期不断完善的

**Comment by gmlymayday** [comment]
整个布局，shape写起来虽然简单，但是多了drawable文件会非常多。

**Comment by lygttpod** [comment]
@gmlymayday @cwyrzz 新版本已发布，支持圆角哦，可以看下效果图及说明文档
