### ISSUE TITLE
能设置drawable图标跟文字居中展示吗

### ISSUE THREAD

**Issue by yxyaxng** [lygttpod/SuperTextView#27]
![image](https://cloud.githubusercontent.com/assets/24906252/26819077/efb216bc-4acf-11e7-94c8-b8282b085f58.png)

**Comment by lygttpod** [comment]
外边在套一层   让stv居中不久行了么

**Comment by VankaIn** [comment]
@lygttpod  感觉这个需求很多啊，如果像你这样说，我还不如用 LinearLayout?

**Comment by lygttpod** [comment]
用CommonTextview里边设置centerview的文字和图片就是居中

**Comment by VankaIn** [comment]
@lygttpod  get, sorry没留意 demo，谢谢了
