### ISSUE TITLE
缺少字体加粗.

### ISSUE THREAD

**Issue by hhhaiai** [lygttpod/SuperTextView#28]
demo里 的最下面一个页面 

cLeftTopTextSize 可以设置字体大小 缺少  cLeftTopTextStyle  (加粗/斜体/下划线等)

可以设置不同方位的字体可以超链不? 比如张三,点击后超链到一个网络地址等操作 局部监听

**Comment by hhhaiai** [comment]
字体行宽 支持自适应吧    局部字体调大导致只显示一半.

**Comment by lygttpod** [comment]
字体加粗目前还没有，你说的超链接之类的可以通过点击事件实现  里边大部分按钮都有自己的点击事件，如果页面不是很复杂，可以使用CommonTextView实现哦 ，里边属性相对全点 @hhhaiai

**Comment by hhhaiai** [comment]
好的.谢谢. 暂时项目没用这些.只是个人建议. 毕竟要做的更好

**Comment by zhuangzeqin** [comment]
支持字体加粗吗？

**Comment by lygttpod** [comment]
@zhuangzeqin 暂不支持，如急需的话可以下载源码稍微修改一下，毕竟源码只有一个类文件，哈哈

**Comment by lygttpod** [comment]
@zhuangzeqin @hhhaiai  SuperTextView2.0.0已上线，支持字体加粗，满足你的要求，欢迎使用并提供意见
