### ISSUE TITLE
怎么获取左边或者右边的string呢？

### ISSUE THREAD

**Issue by SYHQ** [lygttpod/SuperTextView#29]

**Comment by lygttpod** [comment]
@SYHQ  superTextView.getView(SuperTextView.xxxId))获取某个textview，然后就是类似textview的用法了，gettext就行了

**Comment by SYHQ** [comment]
但是我看getView这个方法值返回了case 6和case7的情况

**Comment by SYHQ** [comment]
@lygttpod 但是我看getView这个方法值只返回了case 6和case7的情况

**Comment by lygttpod** [comment]
@SYHQ 如果布局没有用到checkbox 控件的话，建议使用CommonTextView,里边提供的方法更全面，过段时间准备对SuperTextView进行重构，所以如果暂时STV不能满足你的需求的话，可以尝试使用CTV

**Comment by SYHQ** [comment]
@lygttpod 好的，非常感谢
