### ISSUE TITLE
为什么我设置行间距都没有效果呢。

### ISSUE THREAD

**Issue by andansky** [lygttpod/SuperTextView#3]

**Comment by lygttpod** [comment]
@andansky 可以参考文档所有属性列表查看相应设置左右边距的方法

**Comment by andansky** [comment]
只能设置左右边距？我想设置的是上下边距呢。不是有个sBothLineMargin这不是两行间的间距吗？

**Comment by lygttpod** [comment]
@andansky 
    private int topLineMargin;//上边线的左右边距
    private int bottomLineMargin;//下边线的左右边距
    private int bothLineMargin;//两条线的左右边距

你想设置上下边距是想让上线两行字的间距变大吗？方便的话把具体需求发我邮箱lygttpod@163.com
