### ISSUE TITLE
尝试给右边图片添加点击事件

### ISSUE THREAD

**Issue by openandroid9527** [lygttpod/SuperTextView#31]
当有多个条目 需要点击右边图片 没办法判断,不知道楼主有啥好办法

**Comment by lygttpod** [comment]
如果条目中没有使用checkbox的话，目前建议使用CommonTextView，暴露的方法相对多一点


![common](https://user-images.githubusercontent.com/11826777/27111459-de975716-50e2-11e7-80c5-19b66b672555.png)
