### ISSUE TITLE
只设置 左边 字符串，没办法沾满整行

### ISSUE THREAD

**Issue by limjiregister** [lygttpod/SuperTextView#32]
只用app:cLeftTextString这个属性，不用center和right的设置，结果，换行的时候，右边总有一部分空的。怎么设置了？让其正常显示一整行。

**Comment by limjiregister** [comment]
请问，到底如何 很好地显示：  左边 一个标题，，右边一段文字呢？那些对齐换行，好像不太好。

**Comment by lygttpod** [comment]
@limjiregister 
![image](https://user-images.githubusercontent.com/11826777/27167653-77013a7a-51d4-11e7-914d-bd1942616ad5.png)

**Comment by lygttpod** [comment]
@limjiregister 
SuperTextView2.0.0已上线，满足你的要求，欢迎使用并提供意见
