### ISSUE TITLE
神哥，右侧的 checkBox 或者图标 能不能换成一个自定义的 滑动按钮

### ISSUE THREAD

**Issue by ADsuper** [lygttpod/SuperTextView#33]

**Comment by lygttpod** [comment]
@ADsuper 下载源码直接修改一下就可以了，就一个java文件，你可以的，哈哈！

**Comment by ADsuper** [comment]
哥，虽然我知道男人不能说自己不行，奈何实力不足啊     - -

**Comment by lygttpod** [comment]
@ADsuper
 SuperTextView2.0.0已上线，欢迎使用并提供意见
由于自定义View各不相同，即使提供一个方法传入addView传入你的自定义view，代码相对还是比较多的，这样就失去简单使用的意义了，建议特殊布局单独写

**Comment by lygttpod** [comment]
@ADsuper  大兄弟，支持你说的滑动按钮了
4、更新日志

V2.0.1

新增SwitchButton样式  
目前有switchBtn和checkbox两种特殊view

stv:sRightViewType="switchBtn"  
stv:sRightViewType="checkbox"
