### ISSUE TITLE
只有左侧的文本top 和bottom 没有右侧top text 和bottom text 文本显示 属性设置

### ISSUE THREAD

**Issue by zhuangzeqin** [lygttpod/SuperTextView#35]
例如   
   app:sLeftTopTextString="aaaa"
   app:sLeftBottomTextString="aaaaaaaaaaaa"

**Comment by lygttpod** [comment]
如果使用过程中没有用到checkbox的话建议使用CommonTextView，轻量型的STV,但是tv功能比stv更丰富

**Comment by lygttpod** [comment]
@zhuangzeqin SuperTextView2.0.0已上线，满足你的要求，欢迎使用并提供意见
