### ISSUE TITLE
能获取左侧或者右侧的文字吗

### ISSUE THREAD

**Issue by freefly2016** [lygttpod/SuperTextView#36]

**Comment by lygttpod** [comment]
使用CommonTextView可以获取所有textView 的值，如果需求中没有使用CheckBox的话建议使用CommonTextView，暴露的方法更加齐全一点

**Comment by lygttpod** [comment]
@freefly2016 SuperTextView2.0.0已上线，完全满足你的要求，欢迎使用并提供意见
