### ISSUE TITLE
大神我有机会看看你怎么处理RecycleView中superTextview中带checkbox的方案么？

### ISSUE THREAD

**Issue by GiterHuberLover** [lygttpod/SuperTextView#37]
用superTextview写 列表的时候发现没有监听checkbox的方法，怎么处理？

**Comment by lygttpod** [comment]
@GiterHuberLover 没有监听checkbox的方法？？？什么意思，提供的有get和set方法

**Comment by lygttpod** [comment]
@GiterHuberLover 
SuperTextView2.0.0已上线，可以满足你的要求，欢迎使用并提供意见
`
        if (isChecked){
            ((SuperTextView) holder.getView(R.id.super_tv)).setCbChecked(true);
        }else {
            ((SuperTextView) holder.getView(R.id.super_tv)).setCbChecked(false);
        }
        
        ((SuperTextView) holder.getView(R.id.super_tv))
                .setLeftTopString(newsBean.getTitle())
                .setLeftBottomString(newsBean.getTime());
        
        Picasso
                .with(mContext)
                .load(newsBean.getImgUrl())
                .placeholder(R.drawable.head_default)
                .into(((SuperTextView) holder.getView(R.id.super_tv)).getLeftIconIV());
`
