### ISSUE TITLE
将superTextView 作为Cardview 中的子控件时，点击superTextView 区域，消耗掉了父控件CardView的点击响应事件

### ISSUE THREAD

**Issue by lichun-nick** [lygttpod/SuperTextView#38]

**Comment by lygttpod** [comment]
是因为默认开启了点击波纹的特性，点击波纹的效果需要点击事件，所以消耗掉CardView的事件了，下个版本会处理一下，只有开启（useRipple=true）的时候才有点击事件，关掉的话就不消耗事件，这两天会发布一个小版本

**Comment by lygttpod** [comment]
@lichun-nick 新版本已发布，修复了你说的问题，另外加了几个炫酷的功能，可以看下说明文档哦

**Comment by lichun-nick** [comment]
ok
