### ISSUE TITLE
没有直接的java代码来设置文本颜色，比如中间文字的颜色。。。

### ISSUE THREAD

**Issue by imxy** [lygttpod/SuperTextView#39]

**Comment by lygttpod** [comment]
@imxy 
颜色字体大小之类的属性，大部分都是事先确定的吧，直接在xml配置好，你这是要动态改变颜色？？

**Comment by imxy** [comment]
@lygttpod 
是的，要动态改变文字颜色，还是有这个需求的，不过我用了你的commtextview，这个你添加了动态设置文字颜色的方法，谢了哈

**Comment by lygttpod** [comment]
@imxy 已经发布新版本，支持你需要的设置颜色，另外还有一些新特性设置边框，可以看下效果哦

**Comment by imxy** [comment]
@lygttpod 好的

**Comment by Puppy-Love** [comment]
@lygttpod java代码动态设置字体颜色值 会叠加  比如setRightTextColor（）

**Comment by zhaoxiuyu** [comment]
按下弹起 的字体颜色，怎么设置？
