### ISSUE TITLE
楼猪，比如说右边的是一个imageview

### ISSUE THREAD

**Issue by xiaokun19931126** [lygttpod/SuperTextView#4]
而我需要Picasso来加载图片，这个问题怎么解决

**Comment by lygttpod** [comment]
@xiaokun19931126 当前版本还不支持，不过你这种情况会在后续版本陆续实现，请继续关注后续版本

**Comment by xiaokun19931126** [comment]
好吧，加油楼主，我也加入！

**Comment by lygttpod** [comment]
@xiaokun19931126  v1.0.3已经支持Picasso和Glide来加载网络图片了，可以看下文档使用
