### ISSUE TITLE
setRightString 字符串显示不全

### ISSUE THREAD

**Issue by Clark0518** [lygttpod/SuperTextView#40]
当在代码中设置右侧字符串长度稍微有点长时显示不全，但是在布局中写死的字符串可以显示

**Comment by lygttpod** [comment]
@Clark0518 使用代码设置string的时候  要在布局中配置属性
        stv:sRightMaxEms="20"//根据自己需求填写显示字符数

**Comment by lygttpod** [comment]
默认是显示10个字符

**Comment by Clark0518** [comment]
OK, 谢谢
