### ISSUE TITLE
有一个问题，有时候会从正常变成这样

### ISSUE THREAD

**Issue by DoYouLove** [lygttpod/SuperTextView#41]
![image](https://user-images.githubusercontent.com/17930291/28050149-79732408-662e-11e7-9411-dcf74ba85ec5.png)

![image](https://user-images.githubusercontent.com/17930291/28050182-a2a3b680-662e-11e7-8860-3405ac34846b.png)
这个是正常的时候

**Comment by lygttpod** [comment]
没看懂啥意思，麻烦描述清楚一点哈

**Comment by lygttpod** [comment]
@DoYouLove 你的问题解决了吗，没解决的话麻烦在清晰的描述一下问题，这几天会统一修复
