### ISSUE TITLE
stv命名空间

### ISSUE THREAD

**Issue by xiaobailong24** [lygttpod/SuperTextView#42]
```
<com.allen.library.SuperTextView
                android:layout_width="match_parent"
                android:layout_height="80dp"
                stv:sCenterBottomTextColor="@color/colorAccent"
                stv:sCenterBottomTextString="限额说明>>"
                stv:sCenterTopTextString=" "
                stv:sCenterViewGravity="left_center"
                stv:sLeftBottomTextString="招商银行（8888）"
                stv:sLeftIconRes="@drawable/bank_zhao_shang"
                stv:sLeftTopTextString="银行卡支付"
                stv:sLeftViewGravity="left_center"
                stv:sRightCheckBoxRes="@drawable/circular_check_bg"
                stv:sRightViewType="checkbox" />
```
建议将stv命名空间改为app.
因为Android Studio自动导入时，容易将stv命名为**xmlns:stv="http://schemas.android.com/tools"**.
而实际上看了demo的stv为**xmlns:stv="http://schemas.android.com/apk/res-auto"**,
其实就是**xmlns:app="http://schemas.android.com/apk/res-auto"**

**Comment by lygttpod** [comment]
无论是stv还是app  这个命名空间都是可以的，原则上任意命名空间都可以
命名成xxx然后会自动生成xmlns:xxx="http://schemas.android.com/apk/res-auto"
我习惯性的用什么库就把命名空间命名成库的缩写,便于区分，如果你习惯app的话 就直接使用app也是可以的，这和库本身没有关系哦，意思就是你想使用什么命名空间都可以哦，都可以正常使用

**Comment by xiaobailong24** [comment]
感谢您的回复。这个我是明白的，但是就是AS自动导入的时候容易将命名空间导错，这样就起不到效果，需要为每个xml手动添加stv的命名空间，感觉不是很方便。

**Comment by lygttpod** [comment]
整个过程都是自动生成的哦，没有什么不方便的吧，就是使用app的命名空间还是要自动生成哦
![default](https://user-images.githubusercontent.com/11826777/28099409-f27e44f2-66ee-11e7-95cd-7eaa74578a08.gif)

**Comment by xiaobailong24** [comment]
感谢您的指导。我的Android Studio和你的不一样。。。
![gif](https://user-images.githubusercontent.com/9431974/28099607-1f88e4e2-66f0-11e7-8739-e132e646bccc.gif)

**Comment by lygttpod** [comment]
大兄弟  一样的哦  你把默认的app删除了 在自动生成就好了   你已经有了一个app的auto就没法继续生成auto了，删除app的auto在生成就OK啦

**Comment by xiaobailong24** [comment]
好吧，原来这样！那要是别的控件已经使用了app，再导stv就会出现上面那种情况。不过还是谢谢啦
