### ISSUE TITLE
图标点击方法

### ISSUE THREAD

**Issue by dklvip** [lygttpod/SuperTextView#43]
你好，我下请问一下，我在左边或者右边设置了icon，我想添加图标的点击事件如何操作？我尝试获取到icon对应的ImageView，再用它设置监听事件，也没有收到点击事件，想请问一下是否支持？谢谢!

**Comment by lygttpod** [comment]
如果你的图片是设置leftTextView的drawableleft的图片  可以设置leftTextView的点击事件  如果是leftImage的话，暂时没有，我一会儿加上去，会发布一个版本

谢谢提出的问题，我会不断完善！

**Comment by dklvip** [comment]
好的，谢谢！其实我是把这个当标题头使用的，嘿嘿

**Comment by lygttpod** [comment]
已修复，请看升级说明[v2.0.3](https://github.com/lygttpod/SuperTextView/releases)
