### ISSUE TITLE
sRightMaxEms属性无效？

### ISSUE THREAD

**Issue by LegendBMKill** [lygttpod/SuperTextView#44]
xml里设置sRightMaxEms为30   实际还是默认的10？

![image](https://user-images.githubusercontent.com/23694684/28265602-374519fc-6b23-11e7-9acf-9b54f0123808.png)
![image](https://user-images.githubusercontent.com/23694684/28265639-5d3e4be2-6b23-11e7-9b30-c03005e558b3.png)

**Comment by LegendBMKill** [comment]
测试了一下， sRightMaxEms属性只生效一次  多次设置text无效

**Comment by lygttpod** [comment]
@LegendBMKill 已修复  请使用最新版2.0.5   [更新日志](https://github.com/lygttpod/SuperTextView/releases)
