### ISSUE TITLE
SuperText String 显示不全

### ISSUE THREAD

**Issue by xiaobailong24** [lygttpod/SuperTextView#45]
场景：当一个SuperText 的 RightString 设置为“123”，然后重新设置为“1234”时，会出现显示不全的情况，用“...”隐藏的字符

**Comment by lygttpod** [comment]
@xiaobailong24 
你用的是哪个版本的

**Comment by xiaobailong24** [comment]
您好，是2.0.2

**Comment by lygttpod** [comment]
@xiaobailong24 请使用最新版本   2.0.5  [更新说明](https://github.com/lygttpod/SuperTextView/releases)

**Comment by xiaobailong24** [comment]
@lygttpod 好的，感谢。明天试试

**Comment by xiaobailong24** [comment]
@lygttpod 请问目前支持databinding吗？

**Comment by lygttpod** [comment]
@xiaobailong24 对databinding不是很熟悉，没主动对他databinding做过适配，你可以测测看哈

**Comment by xiaobailong24** [comment]
@lygttpod 我测啦。提示不支持哈。有时间我研究研究你的源码，看能不能支持一下。谢谢啦

**Comment by xiaobailong24** [comment]
@lygttpod 还有个问题，像设置 “sLeftMaxEms”可以在xml里配置，但是在代码里是不支持的？

**Comment by xiaobailong24** [comment]
![normal](https://user-images.githubusercontent.com/9431974/28348965-8d79d95c-6c72-11e7-8f58-dc48fb383c8f.JPG)
![error](https://user-images.githubusercontent.com/9431974/28348964-8d785140-6c72-11e7-8587-7cf145e2f93c.JPG)
  就像这样，第一次是正常的（图一）；当刷新一下，就会出现这种问题（图二）。
SuperTextView用的最新版本 2.0.5也会这样，布局使用的RecyclerView，Adapter用的是[BaseRecyclerViewAdapterHelper](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)

**Comment by lygttpod** [comment]
@xiaobailong24 方便发下你设置的Java代码和xml么

**Comment by xiaobailong24** [comment]
您好，方便。感谢支持！
xml布局文件：
```xml
    <com.allen.library.SuperTextView
        android:id="@+id/super_item"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        stv:sLeftTextSize="18sp"
        stv:sRightMaxEms="40"
        stv:sRightTextColor="@color/colorAccent"
        stv:sRightTextSize="18sp"
        />
```
Java代码：
```Java
public class UserAdapter extends BaseBindAdapter<TextContent> {

    public UserAdapter(@LayoutRes int layoutResId, @Nullable List<TextContent> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(BaseBindHolder helper, TextContent item) {
        SuperTextView text = helper.getView(R.id.super_item);
        text.setLeftString(item.getTitle())
                .setRightString(item.getContent());
    }

}
```

**Comment by lygttpod** [comment]
@xiaobailong24
 `
xml中
 stv:sLeftMaxEms="15"
 stv:sRightMaxEms="40"

adapter中
((SuperTextView) holder.getView(R.id.super_tv))
                .setLeftString(newsBean.getTitle())
                .setRightString(newsBean.getTime());
`

**Comment by xiaobailong24** [comment]
@lygttpod 我按照你的方式改了下，还是相同的问题啊。怀疑是RecyclerView Adapter 的复用问题。

**Comment by lygttpod** [comment]
@xiaobailong24   加QQ  460605805

**Comment by flyjin** [comment]
楼上说的问题我也遇到了

**Comment by flyjin** [comment]
列表刷新的时候 文本的宽度会越来越窄

**Comment by flyjin** [comment]
显示不全的问题还是有 2.05版本  它这个现象好像是原本如果问题的个数比较少的话 即使设置了maxEms  代码设置问题时候仍旧无效   但是如果是在xml中添加的文字大于这个或等于你要用代码设置的字的个数的话 就不会出现这个问题了 怀疑是文本宽度的问题

**Comment by lygttpod** [comment]
@flyjin 在列表中使用的问题待我找到解决办法之后会第一时间通知你们

**Comment by flyjin** [comment]
@lygttpod 而且我还发现一个问题 superTv.setCenterString("")  这么设置是没有用的 必须superTv2.setCenterString(" ");  才会把文字清掉

**Comment by lygttpod** [comment]
@flyjin 
![image](https://user-images.githubusercontent.com/11826777/28362070-aa6f2cf2-6cad-11e7-8c86-74f86db9a642.png)

**Comment by lygttpod** [comment]
@flyjin 列表中使用问题及setXXXString("")无效问题已修复，请使用  最新版 2.0.6

**Comment by xiaobailong24** [comment]
@lygttpod ok，问题已解决。感谢！

**Comment by yuxingfafu** [comment]
compile 'com.github.lygttpod:SuperTextView:2.0.9'
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.22'

RecyclerView 使用的时候，setOnItemClickListener不生效

**Comment by yuxingfafu** [comment]
private List<MerchantBean> list=new ArrayList<>();
       mRvMsg.setLayoutManager(new LinearLayoutManager(this));
        mAdapter=new MerchantListAdapter(list);
        mRvMsg.setAdapter(mAdapter);
        mAdapter.notifyDataSetChanged();
        mAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                ToastUtil.showToastShort("点击了"+position);
                Intent it=new Intent(MerchantListActivity.this,MerchantDetailActivity.class);
                startActivity(it);
            }
        });




public class MerchantBean {

    private String name;
    private String id;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}

![image](https://user-images.githubusercontent.com/7764483/28862073-4fadb10a-7796-11e7-9dd9-41144792c869.png)
![image](https://user-images.githubusercontent.com/7764483/28862108-63acae5e-7796-11e7-9619-ae026daf4291.png)

**Comment by lygttpod** [comment]
使用点击事件的时候要去掉SuperTextView的点击效果 sUseRipple=“false
默认开启水波效果 消耗了事件
去掉就行了，想添加按下效果的话sBackgroundDrawableRes传入你的按下效果的drawable就可以了

**Comment by yuxingfafu** [comment]
@lygttpod 谢谢，修改了下可以了

**Comment by xiaobailong24** [comment]
@lygttpod 希望增加代码设置 sRightTvDrawableLeft 属性
