### ISSUE TITLE
无法显示手机的实时布局了

### ISSUE THREAD

**Issue by Iverlei** [lygttpod/SuperTextView#48]
增加了superTextView(2.0.5)在build.gradle后，会出现The following classes could not be instantiated:- android.support.constraint.ConstraintLayout，导致实时布局实例失败

**Comment by lygttpod** [comment]
@Iverlei 我刚试了  没问题  你看看的依赖方式对吗，现在最新版本是2.0.6  欢迎使用最新版

Android Studio导入方法，添加Gradle依赖

   先在项目根目录的 build.gradle 的 repositories 添加:

     allprojects {
         repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
然后在dependencies添加:

        dependencies {
        ...
        compile 'com.github.lygttpod:SuperTextView:2.0.6'
        }

**Comment by Iverlei** [comment]
一样还是不行
![qq20170724-105657](https://user-images.githubusercontent.com/9875136/28506576-ee4bf8b0-705e-11e7-9b42-88bd45a14b72.png)
build.gradle里
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.jakewharton:butterknife:8.7.0'
    compile 'org.litepal.android:core:1.5.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
    compile 'com.github.lygttpod:SuperTextView:2.0.6'
}
我的android studio是2.3.1。去掉SuperTextView才可以预览

**Comment by lygttpod** [comment]
好的，之前没用约束布局做实验，也没发现这个问题，这个问题我会跟踪一下，有结果会第一时间通知你，谢谢你的支持，给你带来不便还请谅解。



lygttpod@163.com
 
发件人： Leibniz
发送时间： 2017-07-24 10:59
收件人： lygttpod/SuperTextView
抄送： lygttpod; Comment
主题： Re: [lygttpod/SuperTextView] 无法显示手机的实时布局了 (#48)
一样还是不行

build.gradle里
dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.android.support:appcompat-v7:25.3.0'
compile 'com.jakewharton:butterknife:8.7.0'
compile 'org.litepal.android:core:1.5.1'
compile 'com.android.support.constraint:constraint-layout:1.0.2'
testCompile 'junit:junit:4.12'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
compile 'com.github.lygttpod:SuperTextView:2.0.6'
}
我的android studio是2.3.1。去掉SuperTextView才可以预览

**Comment by lygttpod** [comment]
布局无法预览 ，你看看编译后安装到真机能否正常显示，我这边看了暂时没找到问题。。。



lygttpod@163.com
 
发件人： lygttpod@163.com
发送时间： 2017-07-24 11:19
收件人： lygttpod/SuperTextView
主题： Re: Re: [lygttpod/SuperTextView] 无法显示手机的实时布局了 (#48)
好的，之前没用约束布局做实验，也没发现这个问题，这个问题我会跟踪一下，有结果会第一时间通知你，谢谢你的支持，给你带来不便还请谅解。



lygttpod@163.com
 
发件人： Leibniz
发送时间： 2017-07-24 10:59
收件人： lygttpod/SuperTextView
抄送： lygttpod; Comment
主题： Re: [lygttpod/SuperTextView] 无法显示手机的实时布局了 (#48)
一样还是不行

build.gradle里
dependencies {
compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.android.support:appcompat-v7:25.3.0'
compile 'com.jakewharton:butterknife:8.7.0'
compile 'org.litepal.android:core:1.5.1'
compile 'com.android.support.constraint:constraint-layout:1.0.2'
testCompile 'junit:junit:4.12'
annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'
compile 'com.github.lygttpod:SuperTextView:2.0.6'
}
我的android studio是2.3.1。去掉SuperTextView才可以预览

**Comment by Iverlei** [comment]
只是无法预览布局，只要引入此库即使布局中没有使用SuperTextView也无法预览但是可以在真机上运行。仍然感谢。

**Comment by lygttpod** [comment]
@Iverlei   视图无法预览的问题已修复

V2.0.8

修复依赖后在布局中无法显示的bug

**Comment by Iverlei** [comment]
Awesome!!!

**Comment by xiaobailong24** [comment]
太好了，困扰我好几天🤣🤣🤣
