### ISSUE TITLE
导包后，视图就不能预览了！

### ISSUE THREAD

**Issue by FynnJason** [lygttpod/SuperTextView#49]
只是导包，导完后，所有的视图都变成纯白色了。

**Comment by lygttpod** [comment]
@FynnJason 
真机跑下看看布局是否正常显示

**Comment by FynnJason** [comment]
真机是正常的，但是不能实时预览视图，很麻烦呀，视图复杂的情况难道一般写，一般还要运行看效果吗？

**Comment by lygttpod** [comment]
@FynnJason 

ok  验证了一下发现这个问题是2.0.3以上版本出现的，我这边会 尽快处理

**Comment by lygttpod** [comment]
@FynnJason   视图无法预览的问题已修复

V2.0.8

修复依赖后在布局中无法显示的bug
