### ISSUE TITLE
似乎在xml文件中加上了clickable=true之后,之后在activity中写点击事件似乎没有反应了？

### ISSUE THREAD

**Issue by panfei008** [lygttpod/SuperTextView#50]
我用的是commonTextView,不知道别人有没有类似的问题 去掉clickable=true就好了

**Comment by lygttpod** [comment]
@panfei008 刚试了 没问题哦
```

  <com.allen.library.CommonTextView
                android:id="@+id/common_tv"
                android:clickable="true"
                android:layout_width="match_parent"
                android:layout_height="80dp"
                ctv:cCenterTextString="张三\n188******88"
                ctv:cCenterTextViewGravity="center"
                ctv:cLeftIconResForDrawableLeft="@mipmap/ic_launcher"
                ctv:cLeftTextString="张三\n188******88"
                ctv:cLeftTextViewGravity="left_center"
                ctv:cRightIconResForDrawableRight="@mipmap/ic_launcher"
                ctv:cRightTextString="张三\n188******88"
                ctv:cRightTextViewGravity="right_center"
                ctv:cSetSingleLine="false"
                ctv:cShowDividerLineType="both"
                ctv:cUseRipple="true" />


 commonTextView.setOnCommonTextViewClickListener(new CommonTextView.OnCommonTextViewClickListener() {
            @Override
            public void onCommonTextViewClick() {
                super.onCommonTextViewClick();
                Toast.makeText(CommonTextViewActivity.this, "onCommonTextViewClick", Toast.LENGTH_LONG).show();
            }

        });
```

**Comment by panfei008** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.panfei.pf.commontextviewtest.MainActivity">

    <com.allen.library.CommonTextView
        android:id="@+id/ctvaaa"
        android:layout_width="match_parent"
        android:layout_height="50dp"

        app:cLeftTextSize="15sp"
        app:cLeftTextString="左边文字"
        app:cLeftViewPaddingLeft="10dp"
        app:cLeftViewPaddingRight="10dp"

        app:cLeftViewIsClickable="true"
        />

</LinearLayout>`
`java文件:`
` CommonTextView commonTextView = (CommonTextView) findViewById(R.id.ctvaaa);
        commonTextView.setLeftViewIsClickable(true)
                .setOnCommonTextViewClickListener(new CommonTextView.OnCommonTextViewClickListener(){
                    @Override
                    public void onCommonTextViewClick() {
                        super.onCommonTextViewClick();
                        Toast.makeText(MainActivity.this,"aaaaasda",Toast.LENGTH_SHORT).show();
                        ////点击的时候并不能每次都能成功,好像是点到文字上就没法显示toast了
                    }
                });



    }`

你看下呢 我之前的描述有问题不好意思哈

**Comment by lygttpod** [comment]
@panfei008 
那是因为你开启了左侧文字的点击事件，默认是false  你写成true了app:cLeftViewIsClickable="true"  就消耗掉整个view的点击事件了，把这句删掉就行了  并且代码中也不要调用commonTextView.setLeftViewIsClickable(true) 就没问题了

**Comment by panfei008** [comment]
@lygttpod 
那我的想法就是 我加入添加了app:cLeftViewIsClickable="true"之后,但是我并没有在java代码中能找到类似点击左侧文字的监听方法.我的意思是这样会不会造成误解?因为我设置app:cLeftViewIsClickable="true"之后从道理上讲我点击后应该会出现响应对吧。但并没有这个方法,因此我点击左侧文字的时候并没有反应。

**Comment by lygttpod** [comment]
@panfei008 

点击事件如何使用 文档里边已经写的很详细了，具体根据需求 使用哪个重写就行了，默认是没有的  因为每个使用者的点击事件不尽相同，所以需要自己根据需求添加想要的点击事件
```
4.点击事件（可根据需求选择实现某个点击事件）

        点击事件配合两种方法使用才有效果

      ①、xml配置使用
            ctv:cLeftViewIsClickable="true"
            ctv:cCenterViewIsClickable="true"
            ctv:cRightViewIsClickable="true"
           
      ②、代码中设置
           commonTextView.setLeftViewIsClickable(true)
                   .setCenterViewIsClickable(true)
                   .setRightViewIsClickable(true)   

     点击事件
    commonTextView.
    setOnCommonTextViewClickListener(new CommonTextView.OnCommonTextViewClickListener(){
                                              @Override
                                              public void onCommonTextViewClick() {
                                                  super.onCommonTextViewClick();
                                                  //do click
                                              }

                                              @Override
                                              public void onLeftViewClick() {
                                                  super.onLeftViewClick();
                                                  //do click
                                              }

                                              @Override
                                              public void onCenterViewClick() {
                                                  super.onCenterViewClick();
                                                  //do click
                                              }

                                              @Override
                                              public void onRightViewClick() {
                                                  super.onRightViewClick();
                                                  //do click
                                              }
                                          });
```

**Comment by panfei008** [comment]
哦好吧,是我看的不仔细,打扰打扰了 - -|||
