### ISSUE TITLE
sBackgroundColor 设置了背景颜色没有效果啊

### ISSUE THREAD

**Issue by jyjiawohao** [lygttpod/SuperTextView#51]
<com.allen.library.SuperTextView
            android:id="@+id/tv02"
            stv:sBackgroundColor="@color/red"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_marginTop="20dp"
            stv:sCenterTextString="登录"
            stv:sRightIconHeight="14dp"
            stv:sRightIconWidth="14dp"
            stv:sUseRipple="true"/>

**Comment by lygttpod** [comment]
@jyjiawohao 
设置背景是这个属性  sBackgroundDrawableRes

你这个应该是早期的版本，请使用最新版 2.0.9，使用过程请参照说明文档
