### ISSUE TITLE
textvie w的文字超过一定长度后不要用省略号，能否做一个标志位判断下?

### ISSUE THREAD

**Issue by yuxingfafu** [lygttpod/SuperTextView#52]
textview的文字超过一定长度后不要用省略号，能否做一个标志位判断下?

**Comment by yuxingfafu** [comment]
![image](https://user-images.githubusercontent.com/7764483/28807182-c29d0f8a-76a6-11e7-8c83-a83a02f09d58.png)

**Comment by lygttpod** [comment]
@yuxingfafu 
可以通知 sCenterMaxEms  控制最多显示多少字
也可以通过 设置sCenterLines设置显示几行
