### ISSUE TITLE
SuperButton 不支持设置背景图吗

### ISSUE THREAD

**Issue by rmtic** [lygttpod/SuperTextView#53]
SuperButton 不支持设置背景图吗 和 圆角

**Comment by lygttpod** [comment]
@rmtic selector里边的drawable你可以自己设置，请参照Demo

**Comment by rmtic** [comment]
我试了不行<com.allen.library.SuperButton
                android:layout_width="70dp"
                android:layout_height="70dp"
                android:layout_margin="5dp"
                android:text="圆角"
                android:background="@drawable/bb"
                stv:sCornersRadius="5dp" />

**Comment by lygttpod** [comment]
@rmtic 请参考Demo，谢谢

**Comment by rmtic** [comment]
大牛，你好！不好意思，打扰你这么多次，SuperButton设置了background并没有显示出图片

**Comment by lygttpod** [comment]
@rmtic 请描述一下你要实现的效果，可以的话配一张效果图我看下能不能实现

**Comment by rmtic** [comment]
我使用的是SuperButton，本人愚笨没找到在哪里可以设置图片，DEMO _里面目前我看到的是可以设置圆角，背景色和渐变，图片上传不了，我只能贴代码：
<com.allen.library.SuperButton
                android:layout_width="70dp"
                android:layout_height="70dp"
                android:layout_margin="5dp"
                android:text="圆角"
                android:background="@mipmap/ic_launcher"
                stv:sCornersRadius="5dp"
                stv:sSolidColor="@color/colorAccent"
                stv:sStrokeColor="#000000"
                stv:sStrokeWidth="1dp"/>

我主要是加了这句话 android:background="@mipmap/ic_launcher"

**Comment by lygttpod** [comment]
@rmtic 抱歉，代码中实现圆角等方法是通过setbackgroung实现的，所以设置 android:background=""之后代码中会重设，导致设置无效。因为之前没有遇到过这样的需求，目前暂不支持设置图片，方便的话把效果图发邮件发我看下，抽时间去完善，谢谢你的支持！

**Comment by lygttpod** [comment]
@rmtic hello  方便的话尽快发下你的效果图，我这边好处理修改

**Comment by rmtic** [comment]
就只圆角按钮 ，添加背景图片，效果如下：

**Comment by lygttpod** [comment]
@rmtic 尴尬，效果如下。。。然后没了，哈哈

**Comment by rmtic** [comment]
刚才图片可能没发成功，你在看看有没有收到

**Comment by lygttpod** [comment]
@rmtic 。。。还是邮箱发我吧

**Comment by rmtic** [comment]
大神，附件已经发送到你的邮箱lygttpod@163.com

**Comment by lygttpod** [comment]
@rmtic 牵扯到图片的问题，暂时没有找到更好的办法处理，因为shape里边没有设置图片的相关属性，而shape又是通过background设置进去的，所有等我找到适当的解决办法再通知你，刚更新了一个版本，你可以看看 [2.1.1更新日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.1.1)

**Comment by rmtic** [comment]
好的，谢谢你！
