### ISSUE TITLE
SuperButton的属性希望在代码里也可以设置

### ISSUE THREAD

**Issue by zhupengxiang** [lygttpod/SuperTextView#55]

**Comment by lygttpod** [comment]
@zhupengxiang OK，下个版本会考虑加进去

**Comment by lygttpod** [comment]
@zhupengxiang 

问题已修复 [2.1.1更新日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.1.1)

**Comment by zhupengxiang** [comment]
ok @lygttpod
