### ISSUE TITLE
对 这个库的一个疑问和勘误&建议

### ISSUE THREAD

**Issue by zhEdward** [lygttpod/SuperTextView#56]
## 疑问
`SuperTextview`  设置了 `stv:sBackgroundDrawableRes` 为一个自带长宽的 切图素材，如果不指定`android:layout_height` 为具体数值就会因自适应而称满全屏。是因为考虑到  其余的属性也设置其相关的 drawable的  在并上`sBackgroundDrawableRes`属性，就导致`SuperTextview` 在“自适应”下计算 高度较为繁琐 切 最终现实效果不如人意。所以才需要 手动指定 `android:layout_xxx` 属性的？

## 勘误 
README.md 中这个可以修正下
![image](https://user-images.githubusercontent.com/12438329/29173412-cb58ca26-7e15-11e7-8be5-00a07c97ff83.png)

## 建议
demo中 关于头像的网络加载那部分，可以考虑额外添加 `glide`搭配 +[glide-transformations](https://github.com/wasabeef/glide-transformations) 做圆形image变换的 例子（再没google之前 我还想提问是否还有其他属性type控制  `stv:sRightIconRes` 和 `stv:sLeftIconRes` 传入image 自动裁剪为 其他形状的疑问）。

**Comment by lygttpod** [comment]
@zhEdward 
1、解惑解答：
     之所以需要指定设置android:layout_height 的值是因为整个view外层是RelativeLayout，中间内容部分高度其实都是自适应的，但由于加了上下两条分割线，两条线的位置分别是parent_top和parent_bottom，如果把跟布局设成自适应，由于添加了parent_top和parent_bottom两个属性，会让它自动铺满全屏，就是你看到的效果，所以需要指定高度来解决这个问题。之前想过跟布局使用LinearLayout，这样导致中间左中右布局定位会出现问题，就没采用，暂时没想到更好的办法处理，就设置固定高度了（PS:你有好的思路的话可以分享一下哦）
2、勘误：
    谢谢你的细心（点个赞），错误部分已经修复。
3、由于加载网络图片框架很多，考虑到使用者会有不同的选择就没封装字底层，把这个权利让使用者去选择。不同的图片库都有自己的方案修改图像，故暂时没提供demo（后期可以在demo中添加上去），也曾想过在自定义Imageview并暴露方法属性对图片进行裁剪，又考虑到有的需要的可能不是圆形，而其他不规则的形状，所以到现在还没下手去写，不过这个需求后期肯定会加上去的，因为我这有这样的需求，哈哈。

再次感谢你的建议及发现的问题，感谢对本库的支持，有好的想法欢迎提出沟通交流哦。
