### ISSUE TITLE
代码setText希望支持CharSequence

### ISSUE THREAD

**Issue by LegendBMKill** [lygttpod/SuperTextView#57]
![image](https://user-images.githubusercontent.com/23694684/29215521-de7ff4f8-7edd-11e7-922d-905aa98f9e01.png)

支持CharSequence可以改变字符串的颜色和大小

**Comment by LegendBMKill** [comment]
谢谢共享~

**Comment by lygttpod** [comment]
@LegendBMKill 多谢建议，下个版本会考虑加进去

**Comment by lygttpod** [comment]
@LegendBMKill 

提的问题已修复

[2.1.1更新日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.1.1)

**Comment by LegendBMKill** [comment]
@lygttpod 棒棒的~
