### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by kinghom** [lygttpod/SuperTextView#60]
设置右边text的时候，如果是数字超过10个的话，超过的就会被隐藏，比如我右边text是身份证号码，则只能显示前面十位，什么情况？

**Comment by lygttpod** [comment]
@kinghom 
> 设置的有默认值，默认2.1.0之前设置的是默认最多10个字符，新版本默认修改为15个字符
具体需要显示多少字符根据自己需求进行设置即可。

sLeftMaxEms | integer | 左边文字显示个数 | 默认15
sLeftTopMaxEms | integer | 左上文字显示个数 | 默认15
sLeftBottomMaxEms | integer | 左下文字显示个数 | 默认15
sCenterMaxEms | integer | 中间文字显示个数 | 默认15
sCenterTopMaxEms | integer | 中上文字显示个数 | 默认15
sCenterBottomMaxEms | integer | 中下文字显示个数 | 默认15
sRightMaxEms | integer | 右边文字显示个数 | 默认15
sRightTopMaxEms | integer | 右上文字显示个数 | 默认15
sRightBottomMaxEms | integer | 右下文字显示个数 | 默认15

**Comment by kinghom** [comment]
好的 非常感谢
