### ISSUE TITLE
能否提供sCenterTvDrawableRight的控制大小

### ISSUE THREAD

**Issue by 957919019** [lygttpod/SuperTextView#61]
![-](https://user-images.githubusercontent.com/19183142/29545615-ed250f4c-8721-11e7-8da9-9f3e59560076.png)

**Comment by lygttpod** [comment]
@957919019 麻烦把你的UI样式或者设计稿顺便也发下，根据样式我会做相应的调整

**Comment by 957919019** [comment]
我是以支付宝3个字为中心，文档里api中有sCenterTvDrawableRight来显示支付宝右侧的图，但是没办法控制大小，也没办法用glide加载，
![default](https://user-images.githubusercontent.com/19183142/29545739-99a9a502-8722-11e7-8c71-a03de3186428.png)

**Comment by lygttpod** [comment]
![image](https://user-images.githubusercontent.com/11826777/29653442-5a423242-88dc-11e7-898f-e6c54092b6ba.png)
新版本已提供相关配置属性设置drawable的宽高
[V2.1.3更新日志](https://github.com/lygttpod/SuperTextView/releases/tag/2.1.3)
```
sLeftTvDrawableWidth | dimension | 左边TextView的drawable的宽度 
sLeftTvDrawableHeight | dimension | 左边TextView的drawable的高度 
sCenterTvDrawableWidth | dimension | 中间TextView的drawable的宽度 
sCenterTvDrawableHeight | dimension | 中间TextView的drawable的高度 
sRightTvDrawableWidth | dimension | 右边TextView的drawable的宽度 
sRightTvDrawableHeight | dimension | 右边TextView的drawable的高度

```

**Comment by 957919019** [comment]
谢谢
