### ISSUE TITLE
android 4.4.4 的滑动按钮有问题，拉长了

### ISSUE THREAD

**Issue by aesion** [lygttpod/SuperTextView#65]

**Comment by lygttpod** [comment]
@aesion 实在模拟器上测试的还是真机测试

**Comment by aesion** [comment]
@lygttpod 真机，华为P6，自定义宽度无效果

**Comment by lygttpod** [comment]
@aesion 我这边咱没找到拉长的原因，你写个原生的switch按钮 按到华为p6上看看是否拉长，验证一下是系统原因还是我这边的原因，我用的就是系统原生的，只是封装了一下，期待你的验证结果

**Comment by aesion** [comment]
手机原因
