### ISSUE TITLE
过渡嵌套问题？

### ISSUE THREAD

**Issue by xybCoder** [lygttpod/SuperTextView#67]
SuperTextView通过动态添加控件，而控件leftViev rightView都是继承RelativeLayout，如果实现一个简单页面（通过RelativeLayout就可以实现），而通过SuperTextView，至少要多嵌套一层，会不会过渡嵌套。

**Comment by xybCoder** [comment]
这些控件能不能做到按需加载

**Comment by lygttpod** [comment]
@xybCoder 
首先SuperTextView是一个功能强大的View，可以满足日常大部分布局样式，既然要满足大部分布局就难免会有一些取舍，因为他要应对各种情况。像稍微复杂点的页面自己写也是多少需要嵌套的，当然如果是非常简单的布局就没必要使用SuperTextView了，他的存在是为了解决某种特定需求的哦。当然代码我这边会不断优化的，感谢你对本库的支持哦

**Comment by xybCoder** [comment]
@lygttpod 嗯，谢谢详细的解释
