### ISSUE TITLE
建议每个字段支持hint，应对表单中的情况

### ISSUE THREAD

**Issue by Rethen** [lygttpod/SuperTextView#68]

**Comment by lygttpod** [comment]
@Rethen 不是输入框一般用不上hint吧，可否来个效果图看看

**Comment by Rethen** [comment]
![4- 3- 3](https://user-images.githubusercontent.com/7802673/30158338-8a043356-93f7-11e7-82bf-86b6a471146d.jpg)

**Comment by lygttpod** [comment]
@Rethen 这样的显示方式很容易实现  因为不是EditText输入框  完全可以使用setRightTextString实现，修改对应文字颜色为灰色即可

**Comment by Rethen** [comment]
请输入比赛名称，这就是EditText啊，background为null的EditText

**Comment by lygttpod** [comment]
@Rethen SuperTextView暂不支持EditText哦

**Comment by BobEve** [comment]
使用setRightTextString实现的话，需要判断，比如字符比较后修改字体颜色，可能还会有其他一些情况需要判断，不如加一个hint字段来的方便优雅

**Comment by gxp3635** [comment]
同意，希望加入Hint字段
