### ISSUE TITLE
多行显示有没有

### ISSUE THREAD

**Issue by assess15** [lygttpod/SuperTextView#69]
第一行显示一部分,第二行显示一部分,就行TextView那样

**Comment by lygttpod** [comment]
@assess15 默认单行显示，提供的有属性控制多行显示，详细用法请参照  Readme文档的属性说明

**Comment by assess15** [comment]
sIsSingLines | boolean | 是否单行显示 这是简书里的,有这个属性,http://www.jianshu.com/p/1a5303258754
GitHub里没有了,从属性中也没有找到,最新的是不是移除了这个属性?

**Comment by lygttpod** [comment]
@assess15 
`

sLeftLines | integer | 左边文字显示行数 | 默认1
sLeftTopLines | integer | 左上文字显示行数 | 默认1
sLeftBottomLines | integer | 左下文字显示行数 | 默认1
sCenterLines | integer | 中间文字显示行数 | 默认1
sCenterTopLines | integer | 中上文字显示行数 | 默认1
sCenterBottomLines | integer | 中下文字显示行数 | 默认1
sRightLines | integer | 右边文字显示行数 | 默认1
sRightTopLines | integer | 右上文字显示行数 | 默认1
sRightBottomLines | integer | 右下文字显示行数 | 默认1
sLeftMaxEms | integer | 左边文字显示个数 | 默认15
sLeftTopMaxEms | integer | 左上文字显示个数 | 默认15
sLeftBottomMaxEms | integer | 左下文字显示个数 | 默认15
sCenterMaxEms | integer | 中间文字显示个数 | 默认15
sCenterTopMaxEms | integer | 中上文字显示个数 | 默认15
sCenterBottomMaxEms | integer | 中下文字显示个数 | 默认15
sRightMaxEms | integer | 右边文字显示个数 | 默认15
sRightTopMaxEms | integer | 右上文字显示个数 | 默认15
sRightBottomMaxEms | integer | 右下文字显示个数 | 默认15


`

**Comment by assess15** [comment]
长按复制有没有这个功能

**Comment by lygttpod** [comment]
@assess15 
长按复制针对需要的位置获取到对应的view后设置   textView.setTextIsSelectable(true);既可
例如：superTextView.getLeftBottomTextView().setTextIsSelectable(true);

**Comment by assess15** [comment]
我怎么只看到有getLeftBottomString()这个方法,没有看到getLeftBottomTextView().setTextIsSelectable(true);方法

**Comment by lygttpod** [comment]
@assess15  
> # 现在最新版是2.1.4   再2.1.2的时候就加上了，请使用最新版本

![image](https://user-images.githubusercontent.com/11826777/30947295-861f9a10-a43b-11e7-9557-982dc3c1d03b.png)

**Comment by assess15** [comment]
好了,就是版本问题,谢谢大神
