### ISSUE TITLE
反馈建议

### ISSUE THREAD

**Issue by TCQQ** [lygttpod/SuperTextView#70]
1. 滑动按钮建议替换成此库，比当前的滑动按钮体验好很多https://github.com/zcweng/SwitchButton
2. 左边和右边建议添加此此控件 可以实现显示圆角头像：https://github.com/hdodenhof/CircleImageView

**Comment by lygttpod** [comment]
@TCQQ 圆角头像的代码前几天已经加过了，并提交到dev分支了，但是遇到一个问题就是，由于自定义属性超过127个导致布局无法预览，只能真机看效果，这样用户体验很不好，所有一直没有合并到master分支上，你可以看dev分支代码酌情使用。待我找到应对方法才能合并到master上

**Comment by rmtic** [comment]
SuperButton,不支持修改成圆形背景图片吗，什么时候支持

**Comment by lygttpod** [comment]
@TCQQ 新版本已经支持圆角头像，内置[CircleImageView](https://github.com/hdodenhof/CircleImageView)，详情请看更新说明[V2.1.5](https://github.com/lygttpod/SuperTextView/releases)

**Comment by TCQQ** [comment]
大赞
