### ISSUE TITLE
superButton 动态设置颜色 会叠加？

### ISSUE THREAD

**Issue by Puppy-Love** [lygttpod/SuperTextView#71]

**Comment by Puppy-Love** [comment]
代码动态设置的颜色 不一样估计和你默认设置那个颜色叠加导致的

**Comment by lygttpod** [comment]
@Puppy-Love 设置哪个颜色出现的问题，我这边跟踪一下代码看看，方便的话贴出有问题的效果图看下

**Comment by Puppy-Love** [comment]
@lygttpod 
![image](https://user-images.githubusercontent.com/16749976/31540242-b85ba592-b03d-11e7-978c-0629bd01a407.png)
![image](https://user-images.githubusercontent.com/16749976/31540267-ca737188-b03d-11e7-8d80-8fb7937076ef.png)
![image](https://user-images.githubusercontent.com/16749976/31540288-d7f1328c-b03d-11e7-83cb-9b83ad1ed362.png)
设置的 白色 和 红色切换，我的设置代码没错吧

**Comment by lygttpod** [comment]
@Puppy-Love 写错了  颜色值要通过getResources获取
这样写
setShapeSolidColor(getResources().getColor(R.color.colorPrimary));

**Comment by Puppy-Love** [comment]
@lygttpod 嗯 是的 多谢了！
