### ISSUE TITLE
V2.1.5 版代码中不存在设置文字大小的方法？

### ISSUE THREAD

**Issue by tomcatnull** [lygttpod/SuperTextView#73]
如题，我想从代码中设置中间文字大小。
SuperTextView.getCenterTextView().setTextSize(sp2px（13）) 设置不太好使设置完文字太大了不止13sp

**Comment by lygttpod** [comment]
@tomcatnull 
这样设置 setTextSize(TypedValue.COMPLEX_UNIT_PX, sp2px（13）);

**Comment by tomcatnull** [comment]
@lygttpod 多谢，解决了
