### ISSUE TITLE
可以添加个superRadio？

### ISSUE THREAD

**Issue by tomcatnull** [lygttpod/SuperTextView#74]
如题。业务上需求需要修改Radio的样式，又要写一堆的xml比较麻烦

**Comment by lygttpod** [comment]
@tomcatnull
#### [Issues](https://github.com/lygttpod/SuperTextView/issues/72)由于自定义属性过多导致继续添加新属性会出现布局无法预览的问题，so 暂时无法添加新属性，待这个问题找到解决办法后再继续补充新属性
## 针对特殊情况建议下载源码稍做修改即可满足自己的需求，毕竟源码修改起来也很简单哦
