### ISSUE TITLE
请问如何设置上下边距？

### ISSUE THREAD

**Issue by StephenCMZ** [lygttpod/SuperTextView#75]
行高wrap_content，请问怎么设置行的上下内边距？

**Comment by lygttpod** [comment]
@StephenCMZ 由于SuperTextView内部有对上下分割线的支持，所以高度需要指定高度不能设置为wrap_content，高度确定之后不建议再修改padding的值，只要高度定好文字就是居中显示的，定高之后需要修改的一般只有文字之间的间距有属性可以修改
sCenterSpaceHeight | dimension | 上中下三行文字的间距 | 默认5dp

强制修改padding的话可以直接使用padding，应为SuperTextView是继承RelativeLayout 的
