### ISSUE TITLE
如何整体居中

### ISSUE THREAD

**Issue by L-CE** [lygttpod/SuperTextView#76]
需求是这样:
![1509539681 1](https://user-images.githubusercontent.com/25133389/32274941-53fbeaf6-bf44-11e7-9c1b-6be525c6290e.png)

现在是这样:
![1509539651 1](https://user-images.githubusercontent.com/25133389/32274939-4fbc66d2-bf44-11e7-8ebf-4be4fc1897d6.png)

**Comment by lygttpod** [comment]
@L-CE 
你这种简单的样式可以直接用一个TextView配合SpannableStringBuilder搞定更方便。
当然用STV也是可以的,设置centerTextString然后配合SpannableStringBuilder实现
