### ISSUE TITLE
当做成列表的时候如何保证上下文字对齐？

### ISSUE THREAD

**Issue by chenkexu** [lygttpod/SuperTextView#79]
![image](https://user-images.githubusercontent.com/14785825/32591996-c02eb6e0-c55c-11e7-8473-ae1c2ae3fea2.png)
由于上下列表的图片大小不一，如何保证上下的文字左对齐？？

**Comment by chenkexu** [comment]
sLeftTvDrawableWidth 这个属性设置怎么不起作用?

**Comment by chenkexu** [comment]
@lygttpod

**Comment by lygttpod** [comment]
设置图片宽高是

sLeftIconWidth | dimension | 左边图片资源的宽度 用于固定图片大小的时候使用 |  
-- | -- | -- | --
sLeftIconHeight | dimension | 左边图片资源的高度 用于固定图片大小的时候使用

**Comment by chenkexu** [comment]
@lygttpod ,这样规定图片宽高无效，是怎么回事

**Comment by Adaclass** [comment]
让UI把图片大小切相同
