### ISSUE TITLE
1.0.4版本编译出错

### ISSUE THREAD

**Issue by ljf1172361058** [lygttpod/SuperTextView#8]
compile 'com.github.lygttpod:SuperTextView:1.0.4'

```
Error:Could not find com.github.lygttpod:SuperTextView:1.0.4.
Required by:
    xxx:unspecified
Search in build.gradle files
```

**Comment by lygttpod** [comment]
看看是不是添加依赖有问题，我这边试了编译没问题。

先在 build.gradle 的 repositories 添加:

    allprojects {
     repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
然后在dependencies添加:

    dependencies {
    ...
    compile 'com.github.lygttpod:SuperTextView:1.0.4'
    }

**Comment by ljf1172361058** [comment]
可以了
