### ISSUE TITLE
 Could not GET 'https://jitpack.io/com/github/lygttpod/SuperTextView/2.1.5/SuperTextView-2.1.5.pom'. Received status code 403 from server: Forbidde

### ISSUE THREAD

**Issue by jyjiawohao** [lygttpod/SuperTextView#81]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve com.github.lygttpod:SuperTextView:2.1.5.
     Required by:
         project :app
      > Could not resolve com.github.lygttpod:SuperTextView:2.1.5.
         > Could not get resource 'https://jitpack.io/com/github/lygttpod/SuperTextView/2.1.5/SuperTextView-2.1.5.pom'.
            > Could not GET 'https://jitpack.io/com/github/lygttpod/SuperTextView/2.1.5/SuperTextView-2.1.5.pom'. Received status code 403 from server: Forbidden

**Comment by lygttpod** [comment]
3、如何使用

3.1、Android Studio导入方法，添加Gradle依赖

   先在项目根目录的 build.gradle 的 repositories 添加:

     allprojects {
         repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
然后在dependencies添加:

        dependencies {
        ...
        compile 'com.github.lygttpod:SuperTextView:2.1.5'
        }

**Comment by jyjiawohao** [comment]
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
     
    }
}
dependencies {
compile 'com.github.lygttpod:SuperTextView:2.1.5'
}
就是这样使用的,

**Comment by lygttpod** [comment]
刚我又新建一个项目，按照集成步骤集成是没问题的，你在试试吧
