### ISSUE TITLE
superButton 代码中设置属性无效

### ISSUE THREAD

**Issue by ADsuper** [lygttpod/SuperTextView#84]
`SuperButton btnLogin;
btnLogin.setShapeSelectorNormalColor(getResources().getColor(R.color.text_default_color));
btnLogin.setShapeSelectorPressedColor(getResources().getColor(R.color.btn_normalColor));
btnLogin.setShapeUseSelector(true);`

但是在布局中设置能生效

**Comment by lygttpod** [comment]
![image](https://user-images.githubusercontent.com/11826777/34398308-d6a3500c-ebb8-11e7-980f-c547ea564356.png)

**Comment by Adaclass** [comment]
大神，此库里面的圆形图片可以拿来使用吗

**Comment by lygttpod** [comment]
@Adaclass 内置的圆形图片就是用的开源库[CircleImageView](https://github.com/hdodenhof/CircleImageView)做了部分属性精简

**Comment by ADsuper** [comment]
尴尬。。是我没看仔细，没注意到 SuperButton_Readme.md ，打扰了！！ - -
