### ISSUE TITLE
代码里面设置Margin

### ISSUE THREAD

**Issue by booldplx** [lygttpod/SuperTextView#88]
为什么代码里面找不到左右Margin设置 还有整个SuperTextView的背景怎么设置没有效果

**Comment by lygttpod** [comment]
1、关于Margin的设置stv没有提供额外的方法，stv本身是一个view，可以按照正常view设置边距的方式进行设置即可。
2、设置背景   
 /**
     * 设置背景
     *
     * @param drawable 背景资源
     * @return 对象
     */
    public SuperTextView setSBackground(Drawable drawable) {
        if (drawable != null) {
            this.setBackgroundDrawable(drawable);
        }
        return this;
    }

**Comment by Adaclass** [comment]
收件箱显示，作者和我不在一个时区。。

**Comment by booldplx** [comment]
背景原来是这样搞........现在还发现代码设置文字颜色也没有效果(item里设置)

**Comment by booldplx** [comment]
颜色搞定了....
