### ISSUE TITLE
sLeftIconMarginLeft影响分割线

### ISSUE THREAD

**Issue by WeissWill** [lygttpod/SuperTextView#9]
sLeftIconMarginLeft和sRightTextMarginRight会影响分割线，这个作用范围用SuperTextView 的MarginLeft和MarginRight就能实现了，而sLeftIconMarginLeft和sRightTextMarginRight应该分别只作用于左边图标和右边Text。

**Comment by lygttpod** [comment]
@WeissWill 不会影响的，分割线是单独设置的，设置分割线左右边距用sTopLineMargin，sBottomLineMargin或者对上下分割线统一设置sBothLineMargin

**Comment by WeissWill** [comment]
sBothLineMargin有默认值？sBottomLineMargin="0dp"就正常了。

**Comment by lygttpod** [comment]
@WeissWill 是的，设置的有默认值，调研了几个app发现很多分割线都有边距，就也加了默认值，
defaultLinePadding = dip2px(context, 16);
        defaultPadding = dip2px(context, 16);
        defaultSize = sp2px(context, 14);
