### ISSUE TITLE
xml 中使用 databinding会报错

### ISSUE THREAD

**Issue by rmtic** [lygttpod/SuperTextView#91]
Error:(55, 45) Cannot find the setter for attribute 'app:sRightTextString' with parameter type java.lang.String on com.allen.library.SuperTextView.

**Comment by lygttpod** [comment]
抱歉，暂时未对databinding做专门的兼容处理

**Comment by chenwuwen** [comment]
> Error:(55, 45) Cannot find the setter for attribute 'app:sRightTextString' with parameter type java.lang.String on com.allen.library.SuperTextView.

在databinding 下会不显示,你那个报错是写错了 应该是stv:sRightTextString而不是app:sRightTextString
