### ISSUE TITLE
SuperButton 如何想改成 SuperTextview是不是直接把button改成textview 就可以呢？

### ISSUE THREAD

**Issue by tianshaokai** [lygttpod/SuperTextView#97]
就是想用textview 实现一个 类似 superbutton 的 功能

**Comment by lygttpod** [comment]
button本身就是继承textview 所以可以替换

**Comment by tianshaokai** [comment]
SuperButton如何在代码里更新某一个属性值呢

**Comment by lygttpod** [comment]
请看文档
![image](https://user-images.githubusercontent.com/11826777/37075086-05459bb2-220b-11e8-8433-cdfdaf9e09bc.png)

**Comment by tianshaokai** [comment]
我看到了你的这种的了，也就是说我随便改变一个属性值，就需要调用setUseShape()方法，有没有快速的方法呢？

**Comment by lygttpod** [comment]
就是在xml中配置属性，源码内部也是会调setUseShape方法的，你动态修改属性就要在最后调setUseShape方法才生效
