### ISSUE TITLE
要是能增加支持wrap_content就好了

### ISSUE THREAD

**Issue by zhumj** [lygttpod/SuperTextView#98]

**Comment by anakin777** [comment]
同意

**Comment by lydlovezjr** [comment]
为什么不支持呀?

**Comment by lygttpod** [comment]
#  做个调研：
* ### wrap_content模式下使用场景有哪些？想使用wrap_content的原因是什么？
* ### 如果支持wrap_content，设置为wrap_content的话，就和普通的布局一样如若不设置各种padding 话内容显示就会很紧凑，还需要手动配置各种padding来达到UI的效果，这样做是否能接受
* ### 是否只是为了内容行数不确定的情况而想使用wrap_content吗？
* ### 如若配置了wrap_content对UI在各个屏幕适配是否有影响？(一般做UI适配都是有固定的宽高)

> ###  我先解释一下之前为何不支持wrap_content：
> ### 因为上下分割线是单独的view，在RelativeLayout中要想保证view在top和bottom的位置就要使用alignParentTop和alignParentBottom属性，如果设置了这两个属性RelativeLayout就会铺满整个屏幕，正因为这个原因才让设置固定高度的

> 悄悄告诉你通过重写分割线的逻辑（使用画笔自己绘制的分割线）目前测试版已经支持wrap_content了，不晓得是否要发版，所以以上问题请如实回答便于完善对wrap_content的支持，测试没问题会考虑发release版

**Comment by Adaclass** [comment]
我觉得不需要吧，一般的使用此控件的时候，会一下铺满整个屏幕，只是给人感觉很不好，，，但设置了固定高度就好看了。

**Comment by 932707629** [comment]
需要呀  在列表里面  文本内容不确定有多少行 设置固定宽高的话 就有一些显示不出来 如果就一行的话还会显得有些空

**Comment by lygttpod** [comment]
### [V2.2.0](https://github.com/lygttpod/SuperTextView/releases/tag/2.2.0)高度支持wrap_content
